---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 cable controllers 
summary: Verkabeln Sie Ihr ASA r2-Speichersystem, um die Clusterkommunikation, den Host-Netzwerkzugriff, die Managementkonnektivität und die Verbindungen zu den Speicherregalen zu ermöglichen. 
---
= Verkabeln Sie die Hardware für Ihr ASA r2 Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verkabeln Sie Ihr ASA r2-Speichersystem, um die Clusterkommunikation, den Host-Netzwerkzugriff, die Managementkonnektivität und die Verbindungen zu den Speicherregalen zu ermöglichen.



[[overview-of-hardware-cabling]]
== Übersicht der Hardwareverkabelung

Die Verkabelung unterscheidet sich je nach Plattformmodell, da jedes ASA r2 Modell über einzigartige Steckplatzpositionen, Portzuordnungen und E/A-Modulkonfigurationen verfügt. Wählen Sie die Vorgehensweise für Ihr ASA r2 Modell:

* link:cable-hardware-a1k.html["Kabel ASA A1K"]
* link:cable-hardware-a70-90.html["Kabel ASA A70 und A90"]
* link:cable-hardware-a20-30-50.html["Kabel ASA A20, A30 und A50"]
* link:cable-hardware-c30.html["Kabel ASA C30"]


Beim Verkabeln der Hardware werden Sie vier Arten von Verbindungen herstellen:

* *Cluster-/HA-Verbindungen*
+
Verbinden Sie die beiden Controller entweder direkt miteinander (Cluster ohne Switches) oder mit Netzwerk-Switches für Cluster (switched Cluster). Diese Verbindungen ermöglichen die Clusterkommunikation und hochverfügbares Failover zwischen Controllerpaaren. Cluster-Interconnect-Datenverkehr und HA-Datenverkehr nutzen dieselben physischen Ports.

* *Host-Netzwerkverbindungen*
+
Verbinden Sie die Controller je nach Hostkonfiguration über Ethernet (iSCSI, NVMe/TCP) oder Fibre Channel (FC, NVMe/FC) mit den SAN-Hosts. Diese Verbindungen ermöglichen den Datenzugriff für Ihre Speicherworkloads.

* *Verwaltungsnetzwerkverbindungen*
+
Verbinden Sie die Controller mit Ihrem Managementnetzwerk, um über ONTAP System Manager und CLI auf die Systemadministration zugreifen zu können.

* *Storage-Shelf-Anschlüsse*
+
Verbinden Sie die Controller mit NS224-Speicherregalen, um Speicherkapazität für Ihr System bereitzustellen.





[[additional-resources]]
== Zusätzliche Ressourcen

Die Verkabelungsanleitungen zeigen gängige Konfigurationen. Die konkrete Verkabelung hängt von den für Ihr Speichersystem bestellten Komponenten ab. Ausführliche Informationen zur Konfiguration und Steckplatzpriorität finden Sie unter link:https://hwu.netapp.com["NetApp Hardware Universe"^].
