---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, cable controllers 
summary: Erfahren Sie, wie Sie die ASA r2-Controller-Kabel an Ihr Netzwerk anschließen und die Controller mit den Shelfs verkabeln. 
---
= Verkabeln Sie die Hardware für Ihr ASA r2 Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Rack-Hardware für das ASA r2 Storage-System installiert haben, installieren Sie die Netzwerkkabel für die Controller und verbinden Sie die Kabel zwischen den Controllern und Storage-Shelfs.

.Bevor Sie beginnen
Prüfen Sie den Pfeil in der Abbildung in den Verkabelungsdiagrammen auf die richtige Ausrichtung der Zuglasche am Kabelanschluss.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[Beispiel für die Ausrichtung der Kabelzuglasche]

* Wenn Sie den Anschluss einsetzen, sollten Sie spüren, dass er einrastet. Wenn Sie ihn nicht einrasten, entfernen Sie ihn, drehen Sie den Kabelkopf um und versuchen Sie es erneut.
* Wenn Sie eine Verbindung zu einem optischen Switch herstellen, stecken Sie den SFP-Transceiver (Small Form-Factor Pluggable) in den Controller-Port ein, bevor Sie den Port verkabeln.




== Schritt 1: Verbinden Sie die Storage Controller mit Ihrem Netzwerk

Verbinden Sie Ihre Controller direkt miteinander und mit Ihrem Host-Netzwerk.

.Bevor Sie beginnen
Wenden Sie sich an Ihren Netzwerkadministrator, um Informationen zum Anschließen des Speichersystems an die Host-Netzwerk-Switches zu erhalten.

.Über diese Aufgabe
Diese Verfahren zeigen gängige Konfigurationen. Die jeweilige Verkabelung hängt von den für das Speichersystem bestellten Komponenten ab. Ausführliche Informationen zur Konfiguration und zur Steckplatzpriorität finden Sie unter link:https://hwu.netapp.com["NetApp Hardware Universe"^].

[role="tabbed-block"]
====
.ASA A1K
--
Verbinden Sie die Storage Controller miteinander, um die ONTAP-Cluster-Verbindungen zu erstellen, und verbinden Sie dann die Ethernet-Ports auf jedem Controller mit dem Host-Netzwerk.

.Schritte
. Verwenden Sie das Cluster/HA-Verbindungskabel, um die Ports e1a mit e1a und die Ports e7a mit e7a zu verbinden.
+

NOTE: Der Cluster-Interconnect-Verkehr und der HA Traffic nutzen dieselben physischen Ports.

+
.. Schließen Sie den Port e1a an Controller A an den Port E1A an Controller B. an
.. Verbinden Sie Port e7a an Controller A mit Port E1A an Controller B.
+
*Cluster/HA Verbindungskabel*

+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cluster HA-Kabel]

+
image::../media/drw_a1k_tnsc_cluster_cabling_ieops-1648.svg[Verkabelungsdiagramm für Cluster mit zwei Nodes ohne Switches]



. Verbinden Sie die Ethernet-Modulports mit Ihrem Hostnetzwerk.
+
Im Folgenden finden Sie einige typische Beispiele für eine Verkabelung im Host-Netzwerk. Informationen zu Ihrer spezifischen Systemkonfiguration finden Sie unter link:https://hwu.netapp.com["NetApp Hardware Universe"^] .

+
.. Verbinden Sie die Ports e9a und e9b wie in der Abbildung dargestellt mit dem Ethernet-Datennetzwerk-Switch.
+

NOTE: Verwenden Sie für maximale Systemperformance für Cluster- und HA-Datenverkehr die Ports e1b und e7b nicht für Host-Netzwerkverbindungen. Verwenden Sie eine separate Hostkarte, um die Leistung zu maximieren.

+
*100-GbE-Kabel*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100-GB-Ethernet-Kabel]

+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[Kabel zum 100-GB-Ethernet-Netzwerk]

.. Verbinden Sie Ihre 10/25 GbE Host-Netzwerk-Switches.
+
*10/25 GbE Host*

+
image::../media/oie_cable_sfp_gbe_copper.svg[10 GB Ethernet-Kabel]

+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[Kabel zu 10/25-GB-Ethernet-Netzwerk]



. Verwenden Sie die 1000BASE-T RJ-45-Kabel, um die Controller-Management-Ports (Schraubenschlüssel) mit den Management-Netzwerk-Switches zu verbinden.
+
image::../media/oie_cable_rj45.svg[RJ-45-Kabel]

+
* 1000BASE-T RJ-45 KABEL*

+
image::../media/drw_a1k_management_connection_ieops-1651.svg[Stellen Sie eine Verbindung mit dem Managementnetzwerk her]




IMPORTANT: Stecken Sie die Netzkabel noch nicht ein.

--
.ASA A70 und ASA A90
--
Verbinden Sie die Storage Controller miteinander, um die ONTAP-Cluster-Verbindungen zu erstellen, und verbinden Sie dann die Ethernet-Ports auf jedem Controller mit dem Host-Netzwerk.

.Schritte
. Verwenden Sie das Cluster/HA-Verbindungskabel, um die Ports e1a mit e1a und die Ports e7a mit e7a zu verbinden.
+

NOTE: Der Cluster-Interconnect-Verkehr und der HA Traffic nutzen dieselben physischen Ports.

+
.. Schließen Sie den Port e1a an Controller A an den Port E1A an Controller B. an
.. Verbinden Sie Port e7a an Controller A mit Port E1A an Controller B.
+
*Cluster/HA Verbindungskabel*

+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cluster HA-Kabel]



+
image::../media/drw_70-90_tnsc_cluster_cabling_ieops-1653.svg[Verkabelungsdiagramm für Cluster mit zwei Nodes ohne Switches]

. Verbinden Sie die Ethernet-Modulports mit Ihrem Hostnetzwerk.
+
Im Folgenden finden Sie einige typische Beispiele für eine Verkabelung im Host-Netzwerk. Informationen zu Ihrer spezifischen Systemkonfiguration finden Sie unter link:https://hwu.netapp.com["NetApp Hardware Universe"^] .

+
.. Verbinden Sie die Ports e9a und e9b wie in der Abbildung dargestellt mit dem Ethernet-Datennetzwerk-Switch.
+

NOTE: Verwenden Sie für maximale Systemperformance für Cluster- und HA-Datenverkehr die Ports e1b und e7b nicht für Host-Netzwerkverbindungen. Verwenden Sie eine separate Hostkarte, um die Leistung zu maximieren.

+
*100-GbE-Kabel*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100-GB-Ethernet-Kabel]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Kabel zum 100-GB-Ethernet-Netzwerk]

.. Verbinden Sie Ihre 10/25 GbE Host-Netzwerk-Switches.
+
*4 Ports, 10/25 GbE Host*

+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25-GB-Kabel]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Kabel zum 100-GB-Ethernet-Netzwerk]



. Verwenden Sie die 1000BASE-T RJ-45-Kabel, um die Controller-Management-Ports (Schraubenschlüssel) mit den Management-Netzwerk-Switches zu verbinden.
+
image::../media/oie_cable_rj45.svg[RJ45-Kabel]

+
* 1000BASE-T RJ-45 KABEL*

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Stellen Sie eine Verbindung mit dem Managementnetzwerk her]




IMPORTANT: Stecken Sie die Netzkabel noch nicht ein.

--
====


== Schritt 2: Anschließen der Storage-Controller an die Storage-Shelfs

Die folgenden Verkabelungsverfahren zeigen, wie Sie Ihre Controller mit einem Shelf und zwei Shelfs verbinden. Sie können bis zu vier Shelfs direkt mit Ihren Controllern verbinden.

[role="tabbed-block"]
====
.ASA A1K
--
Wählen Sie eine der folgenden Verkabelungsoptionen, die Ihrem Setup entsprechen.

.Option 1: Verbinden der Controller mit einem NS224 Storage-Shelf
[%collapsible]
=====
Verbinden Sie jeden Controller mit den NSM-Modulen im NS224-Shelf. Die Grafik zeigt die Verkabelung von den einzelnen Controllern: Die Verkabelung von Controller A wird blau und die Verkabelung von Controller B gelb dargestellt.

.Schritte
. Verbinden Sie auf Controller A die folgenden Ports:
+
.. Verbinden Sie Port e11a mit NSM A Port e0a.
.. Verbinden Sie Port e11b mit Port NSM B Port e0b.
+
image:../media/drw_a1k_1shelf_cabling_a_ieops-1703.svg["Controller A e11a und e11b zu einem einzelnen NS224 Shelf"]



. Verbinden Sie an Controller B die folgenden Ports:
+
.. Verbinden Sie Port e11a mit NSM B Port e0a.
.. Verbinden Sie Port e11b mit NSM A Port e0b.
+
image:../media/drw_a1k_1shelf_cabling_b_ieops-1704.svg["Verkabeln Sie die Controller B-Ports e11a und e11b mit einem NS224-Shelf"]





=====
.Option 2: Verbinden der Controller mit zwei NS224 Storage-Shelfs
[%collapsible]
=====
Verbinden Sie jeden Controller mit den NSM-Modulen beider NS224-Shelfs. Die Grafik zeigt die Verkabelung von den einzelnen Controllern: Die Verkabelung von Controller A wird blau und die Verkabelung von Controller B gelb dargestellt.

.Schritte
. Verbinden Sie auf Controller A die folgenden Ports:
+
.. Verbinden Sie Port e11a mit Shelf 1 NSM A Port e0a.
.. Verbinden Sie den Port e11b mit dem Shelf 2 NSM B-Port e0b.
.. Verbinden Sie Port e10a mit Shelf 2 NSM A Port E0a.
.. Verbinden Sie Port e10b mit Shelf 1 NSM A Port e0b.
+
image:../media/drw_a1k_2shelf_cabling_a_ieops-1705.svg["Controller-zu-Shelf-Verbindungen für Controller A"]



. Verbinden Sie an Controller B die folgenden Ports:
+
.. Verbinden Sie Port e11a mit Shelf 1 NSM B Port e0a.
.. Verbinden Sie Port e11b mit Shelf 2 NSM A Port e0b.
.. Verbinden Sie Port e10a mit Shelf 2 NSM B Port e0a.
.. Verbinden Sie Port e10b mit Shelf 1 NSM A Port e0b.
+
image:../media/drw_a1k_2shelf_cabling_b_ieops-1706.svg["Controller-zu-Shelf-Verbindungen für Controller B"]





=====
--
.ASA A70 und ASA A90
--
Wählen Sie eine der folgenden Verkabelungsoptionen, die Ihrem Setup entsprechen.

.Option 1: Verbinden der Controller mit einem NS224 Storage-Shelf
[%collapsible]
=====
Verbinden Sie jeden Controller mit den NSM-Modulen im NS224-Shelf. Die Grafik zeigt die Verkabelung von den einzelnen Controllern: Die Verkabelung von Controller A wird blau und die Verkabelung von Controller B gelb dargestellt.

*100 GbE QSFP28 Kupferkabel*

image::../media/oie_cable100_gbe_qsfp28.svg[100-GbE-QSFP28-Kupferkabel]

.Schritte
. Verbinden Sie den Controller A-Port e11a mit dem NSM A-Port e0a.
. Verbinden Sie den Controller A-Port e11b mit dem Port NSM B Port e0b.
+
image:../media/drw_a70-90_1shelf_cabling_a_ieops-1731.svg["Controller A e11a und e11b zu einem einzelnen NS224 Shelf"]

. Verbinden Sie den Port e11a von Controller B mit dem Port e0a von NSM B.
. Verbinden Sie den Port e11b des Controllers B mit dem Port e0b des NSM A.
+
image:../media/drw_a70-90_1shelf_cabling_b_ieops-1732.svg["Controller B e11a und e11b zu einem einzelnen NS224 Shelf"]



=====
.Option 2: Verbinden der Controller mit zwei NS224 Storage-Shelfs
[%collapsible]
=====
Verbinden Sie jeden Controller mit den NSM-Modulen beider NS224-Shelfs. Die Grafik zeigt die Verkabelung von den einzelnen Controllern: Die Verkabelung von Controller A wird blau und die Verkabelung von Controller B gelb dargestellt.

*100 GbE QSFP28 Kupferkabel*

image::../media/oie_cable100_gbe_qsfp28.svg[100-GbE-QSFP28-Kupferkabel]

.Schritte
. Verbinden Sie auf Controller A die folgenden Ports:
+
.. Verbinden Sie Port e11a mit Shelf 1, NSM A Port e0a.
.. Verbinden Sie den Port e11b mit Shelf 2, den NSM B Port e0b.
.. Verbinden Sie Port e8a mit Shelf 2, NSM A Port e0a.
.. Verbinden Sie Port e8b mit Shelf 1, NSM B Port e0b.
+
image:../media/drw_a70-90_2shelf_cabling_a_ieops-1733.svg["Controller-zu-Shelf-Verbindungen für Controller A"]



. Verbinden Sie an Controller B die folgenden Ports:
+
.. Verbinden Sie Port e11a mit Shelf 1, NSM B Port e0a.
.. Verbinden Sie Port e11b mit Shelf 2, NSM A Port e0b.
.. Verbinden Sie Port e8a mit Shelf 2, NSM B Port e0a.
.. Verbinden Sie Port e8b mit Shelf 1, NSM A Port e0b.
+
image:../media/drw_a70-90_2shelf_cabling_b_ieops-1734.svg["Controller-zu-Shelf-Verbindungen für Controller B"]





=====
--
====
.Was kommt als Nächstes?
Nachdem Sie die Speicher-Controller mit Ihrem Netzwerk verbunden und dann die Controller mit Ihren Speicher-Shelfs verbunden haben, Sie link:power-on-hardware.html["Schalten Sie das ASA r2-Speichersystem ein"].
