---
sidebar: sidebar 
permalink: install-setup/prepare-hardware.html 
keywords: prepare, hardware installation, aff a1k, aff a70, aff a90, aff c80, asa r2, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50 
summary: Bereiten Sie die Installation des ASA r2 Storage-Systems in Ihrer ONTAP Umgebung vor und registrieren Sie die Hardware, um Zugriff auf Support-Vorteile zu erhalten. 
---
= Bereiten Sie die Installation eines ASA r2-Speichersystems vor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bereiten Sie die Installation Ihres ASA r2-Speichersystems vor, indem Sie den Standort vorbereiten, die Kartons auspacken, den Inhalt der Kartons mit dem Packzettel vergleichen und das System registrieren, um auf die Supportvorteile zuzugreifen.



== Schritt 1: Bereiten Sie den Standort vor

Um Ihr ASA r2-Speichersystem zu installieren, stellen Sie sicher, dass der Standort und der Schrank oder das Rack, den Sie verwenden möchten, den Spezifikationen für Ihre Konfiguration entsprechen.

.Schritte
. Mit https://hwu.netapp.com["NetApp Hardware Universe"^] können Sie überprüfen, ob Ihr Standort die Umwelt- und elektrischen Anforderungen für Ihr Speichersystem erfüllt.
. Stellen Sie sicher, dass Sie ausreichend Platz im Schrank oder Rack für Ihr Speichersystem, Ihre Regale und alle Switches haben:
+
[role="tabbed-block"]
====
.A1K
--
** 4 HE in einer HA-Konfiguration
** 2 HE für jedes NS224 Storage-Shelf
** 1 HE für die meisten Switches


--
.A70 und A90
--
** 4 HE in einer HA-Konfiguration
** 2 HE für jedes NS224 Storage-Shelf
** 1 HE für die meisten Switches


--
.A20, A30 UND A50
--
** 2 HE für ein Storage-System
** 2 HE für jedes NS224 Storage-Shelf
** 1 HE für die meisten Switches


--
====


. Installieren Sie alle erforderlichen Netzwerk-Switches.
+
Installationsanweisungen und Kompatibilitätsinformationen finden Sie im https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Switch-Dokumentation"^] link:https://hwu.netapp.com["NetApp Hardware Universe"^] .





== Schritt 2: Auspacken der Boxen

Nachdem Sie sichergestellt haben, dass der Standort und der Schrank oder das Rack, den Sie für Ihr ASA r2-Speichersystem verwenden möchten, die erforderlichen Spezifikationen erfüllen, packen Sie alle Kartons aus und vergleichen Sie den Inhalt mit den Artikeln auf dem Packzettel.

.Schritte
. Öffnen Sie sorgfältig alle Kartons und legen Sie den Inhalt in einer organisierten Art und Weise.
. Vergleichen Sie den Inhalt, den Sie ausgepackt haben, mit der Liste auf dem Packzettel. Wenn Abweichungen auftreten, notieren Sie sie für weitere Maßnahmen.
+
Sie können Ihre Packliste erhalten, indem Sie den QR-Code auf der Seite des Versandkartons scannen.

+
Die folgenden Elemente sind einige der Inhalte, die Sie in den Feldern sehen können.

+
[cols="12,9,4"]
|===


| *Hardware* | * Kabel* |  


 a| 
** Blende
** Storage-System
** Schienensätze mit Anweisungen (optional)
** Lagerregal (wenn Sie zusätzlichen Speicher bestellt haben)

 a| 
** Management-Ethernet-Kabel (RJ-45-Kabel)
** Netzwerkkabel
** Stromkabel
** Speicherkabel (wenn Sie zusätzlichen Speicher bestellt haben)
** Serielles USB-C-Anschlusskabel

|  
|===




== Schritt 3: Registrieren Sie Ihr Storage-System

Nachdem Sie sichergestellt haben, dass Ihr Standort die Anforderungen für Ihre ASA r2 Storage-Systemspezifikationen erfüllt und überprüft haben, dass alle von Ihnen bestellten Teile vorhanden sind, sollten Sie Ihr System registrieren.

.Schritte
. Suchen Sie nach den Seriennummern für Ihr Storage-System.
+
Die Seriennummern finden Sie an folgenden Stellen:

+
** Auf dem Packzettel
** In Ihrer Bestätigungs-E-Mail
** Auf jedem Controller oder bei einigen Systemen auf dem Systemmanagementmodul jedes Controllers
+
image::../media/drw_ssn_label.svg[Beispiel für die Seriennummer des Systems]



. Gehen Sie zum http://mysupport.netapp.com/["NetApp Support-Website"^].
. Ermitteln Sie, ob Sie Ihr Storage-System registrieren müssen:
+
[cols="1a,2a"]
|===
| Wenn Sie ein... | Führen Sie die folgenden Schritte aus... 


 a| 
Bestehender NetApp Kunde
 a| 
.. Melden Sie sich mit Ihrem Benutzernamen und Passwort an.
.. Wählen Sie *Systeme* > *Eigene Systeme*.
.. Bestätigen Sie, dass die neue Seriennummer aufgeführt ist.
.. Wenn die Seriennummer nicht aufgeführt ist, folgen Sie den Anweisungen für neue NetApp Kunden.




 a| 
Neuer NetApp Kunde
 a| 
.. Klicken Sie auf *Jetzt registrieren* und erstellen Sie ein Konto.
.. Wählen Sie *Systeme* > *Systeme Registrieren*.
.. Geben Sie die Seriennummer des Storage-Systems und die angeforderten Details ein.


Nach der Registrierung können Sie die erforderliche Software herunterladen. Der Genehmigungsprozess kann bis zu 24 Stunden in Anspruch nehmen.

|===


.Was kommt als Nächstes?
Nachdem Sie die Installation Ihrer ASA r2-Hardware vorbereitet haben, können Sie link:deploy-hardware.html["Installieren Sie die Hardware für Ihr ASA r2-Speichersystem"].
