---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Aktivieren Sie den Datenzugriff von SAN-Hosts auf Ihr ASA r2 Storage-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den Datenzugriff einzurichten, sollten Sie sicherstellen, dass die kritischen Parameter und Einstellungen auf Ihrem SAN-Client für den ordnungsgemäßen Betrieb mit ONTAP korrekt konfiguriert sind. Wenn Sie Storage für Ihre VMware-Umgebung bereitstellen, sollten Sie OTV 10.3 installieren, um Ihren ASA r2-Speicher einfach zu verwalten.



== Richten Sie den Datenzugriff von SAN-Hosts ein

Die für die Einrichtung des Datenzugriffs auf Ihrem ASA r2-System über Ihre SAN-Hosts erforderliche Konfiguration variiert je nach Host-Betriebssystem und Protokoll. Die richtige Konfiguration ist für die beste Performance und ein erfolgreiches Failover von großer Bedeutung.

link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSI-Clients"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMe Clients"^]link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Andere SAN-Clients"^]Informationen zur ordnungsgemäßen Konfiguration Ihrer Hosts für die Verbindung mit Ihrem ASA r2-System finden Sie in der Dokumentation zu ONTAP-SAN-Hosts für und.



== Migrieren Sie virtuelle VMware-Maschinen

Wenn Sie Ihren VM-Workload von einem ASA Storage-System auf ein ASA r2 Storage-System migrieren müssen, empfiehlt NetApp die Verwendung link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion"^] für eine Live-Migration Ihrer Daten ohne Unterbrechungen.



== Migrieren Sie Daten aus einem Speichersystem eines Drittanbieters

Ab ONTAP 9.17.1 können Sie mit Foreign LUN Import (FLI) Daten von einer LUN auf einem Drittanbieter-Speichersystem auf ein ASA R2-System migrieren. Durch die Verwendung von FLI für Ihre Datenmigration können Sie das Risiko von Datenverlust und Ausfallzeiten während des Migrationsprozesses minimieren.

FLI unterstützt sowohl Online- als auch Offline-Migrationen. Bei einer Online-Migration bleibt das Client-System online, während Daten vom Drittanbieter-Speichersystem auf das ONTAP -Speichersystem kopiert werden. Online-Migrationen werden von Windows-, Linux- und ESXi-Hostbetriebssystemen unterstützt. Bei einer Offline-Migration wird das Client-System offline genommen, die LUN-Daten werden vom Drittanbieter-Speichersystem auf das ONTAP -Speichersystem kopiert und anschließend wieder online geschaltet.

* Erfahren Sie, wie Sie eine link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["FLI Offline-Migration"^] .
* Erfahren Sie, wie Sie eine link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["FLI Online-Migrationen"^] .




== Konfigurieren Sie Ihr ASA r2-System als Storage-Provider in Ihrer VMware-Umgebung

Mit ONTAP Tools für VMware können Sie Ihr ASA r2 System problemlos als Storage-Anbieter in Ihrer VMware Umgebung einrichten.

ONTAP Tools for VMware vSphere ist ein Satz von Tools, die in Verbindung mit der virtuellen VMware vCenter Server-Appliance (vCSA) für ein einfaches Management von Virtual Machines auf Ihren VMware ESXi-Hosts eingesetzt werden können.

ASA r2-Systeme werden von  und höher unterstütztlink:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["ONTAP Tools für VMware vSphere 10.3"^].

Erfahren Sie, wie Sie Folgendes tun können, link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Implementieren Sie ONTAP-Tools für VMware"^] und verwenden Sie es dann, um Folgendes zu tun:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Fügen Sie vCenter Server-Instanzen hinzu"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["Konfigurieren Sie die ESXi-Hosteinstellungen"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["Ermitteln Sie Ihr ASA r2 Storage-System und Ihre Hosts"^]


.Was kommt als Nächstes?
Sie sind bereitlink:../manage-data/provision-san-storage.html["Bereitstellung von Storage"], Ihren SAN-Hosts das Lesen und Schreiben von Daten auf Speichereinheiten zu ermöglichen.
