---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Sie können den Onboard-Schlüsselmanager von ONTAP in Ihrem ASA r2-System oder einen externen Schlüsselmanager oder beide (in einem Fall) für die Verwaltung der Datenverschlüsselung verwenden.' 
---
= Migration von ONTAP Datenverschlüsselungsschlüsseln zwischen Schlüsselmanagern auf ASA r2 Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Datenverschlüsselungsschlüssel mit dem ONTAP onboard key manager auf Ihrem ASA r2-System, einem externen Schlüsselmanager oder in unterstützten Konfigurationen mit beiden verwalten. Externe Schlüsselmanager werden nur auf Storage-VM-Ebene unterstützt. Auf ONTAP Cluster-Ebene kann entweder der onboard key manager oder ein externer Schlüsselmanager verwendet werden.

[cols="2,2"]
|===
| Wenn Sie Ihren Schlüsselmanager im... | Sie können... 


| Nur Cluster-Ebene  a| 
Entweder dem Onboard-Schlüsselmanager oder einem externen Schlüsselmanager



| Nur auf Speicher-VM-Ebene | Nur ein externer Schlüsselmanager 


 a| 
Sowohl auf Cluster- als auch auf Speicher-VM-Ebene
 a| 
Eine der folgenden Kombinationen von Schlüsselmanagern:

* Option 1
+
Cluster-Ebene: Onboard-Schlüsselmanager

+
Speicher-VM-Ebene: Externer Schlüsselmanager

* Option 2
+
Cluster-Ebene: Externer Schlüsselmanager

+
Speicher-VM-Ebene: Externer Schlüsselmanager



|===


[[migrate-keys-between-key-managers-at-the-ontap-cluster-level]]
== Migrieren Sie Schlüssel zwischen Schlüsselmanagern auf ONTAP-Cluster-Ebene

Ab ONTAP 9.16.1 ist es möglich, die ONTAP Befehlszeilenschnittstelle (CLI) zu verwenden, um Schlüssel auf Clusterebene zwischen Schlüsselmanagern zu migrieren.

[role="tabbed-block"]
====
.Vom integrierten Schlüsselmanager zum externen Schlüsselmanager
--
.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Erstellen Sie eine inaktive externe Schlüsselmanager-Konfiguration:
+
[source, cli]
----
security key-manager external create-config
----
. Wechseln Sie zum externen Schlüsselmanager:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. Löschen Sie die Onboard-Schlüsselmanager-Konfiguration:
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. Legen Sie die Berechtigungsebene auf admin fest:
+
[source, cli]
----
set -privilege admin
----


--
.Vom externen Schlüsselmanager zum integrierten Schlüsselmanager
--
.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Erstellen einer inaktiven Onboard-Schlüsselmanager-Konfiguration:
+
[source, cli]
----
security key-manager onboard create-config
----
. Aktivieren der Onboard-Konfiguration für Verschlüsselungsmanagement:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. Die Konfiguration des externen Schlüsselmanagers löschen
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. Legen Sie die Berechtigungsebene auf admin fest:
+
[source, cli]
----
set -privilege admin
----


--
====


[[migrate-keys-between-key-managers-across-ontap-cluster-and-storage-vm-levels]]
== Schlüsselmanagement auf ONTAP-Cluster- und Storage-VM-Ebene migrieren

Die ONTAP Befehlszeilenschnittstelle (CLI) kann verwendet werden, um Schlüssel zwischen Schlüsselmanagern auf Cluster- und Storage-VM-Ebene zu migrieren.

.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
[source, cli]
----
set -privilege advanced
----
. Migrieren der Schlüssel:
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. Legen Sie die Berechtigungsebene auf admin fest:
+
[source, cli]
----
set -privilege admin
----

