---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Erfahren Sie, wie Sie die Aufbewahrungszeiträume von ARP-Snapshots an Ihre Speicher- und Geschäftsanforderungen anpassen. 
---
= Ändern Sie die Aufbewahrungsfristen für ARP/AI-Snapshots auf ASA R2-Speichersystemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der autonome Ransomware-Schutz mit künstlicher Intelligenz (ARP/KI) ungewöhnliche Aktivitäten auf einem oder mehreren Speichereinheiten Ihres ASA r2 Systems erkennt, wird automatisch ein ARP Snapshot zum Schutz der Daten erstellt. Abhängig von Ihrer Speicherkapazität und Ihren geschäftlichen Anforderungen kann es sinnvoll sein, die standardmäßige ARP Snapshot-Aufbewahrungsdauer zu erhöhen oder zu verringern. So kann beispielsweise die Aufbewahrungsdauer für geschäftskritische Anwendungen verlängert werden, um längere Datenwiederherstellungsfenster zu unterstützen, oder für nicht kritische Anwendungen verkürzt werden, um Speicherplatz zu sparen.

Die standardmäßige Aufbewahrungsdauer für den ARP-Snapshot variiert je nach der Aktion, die Sie als Reaktion auf die abnormale Aktivität ergreifen.

[cols="2,2"]
|===
| Wenn Sie diese Aktion ausführen ... | ARP-Snapshots werden standardmäßig aufbewahrt für... 


| Als falsch positiv markieren | 12 Stunden 


| Als potenziellen Ransomware-Angriff markieren | 7 Tage 


| Ergreifen Sie keine sofortigen Maßnahmen | 10 Tage 
|===
Die Standardaufbewahrungsfristen lassen sich mit der ONTAP Befehlszeilenschnittstelle (CLI) anpassen. Siehe  https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Optionen für automatische ONTAP -Snapshots ändern"] für die Schritte zur Änderung der Standardaufbewahrungsfrist.
