---
sidebar: sidebar 
permalink: secure-data/pause-resume-anti-ransomware-protection.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, pause, resume, suspend 
summary: Wenn Sie ein ungewöhnliches Arbeitslast-Ereignis planen, können Sie ARP mit KI-Analyse vorübergehend aussetzen, um Fehlalarme bei der Erkennung von Ransomware-Angriffen zu verhindern. 
---
= ARP/AI-Schutz auf ASA r2 Speichersystemen pausieren oder fortsetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.17.1 kann der Autonomous Ransomware Protection mit Artificial Intelligence (ARP/AI) zum Schutz von Daten auf dem ASA r2 System verwendet werden. Bei der Planung eines ungewöhnlichen Workload-Ereignisses besteht die Möglichkeit, die ARP/AI-Analyse vorübergehend auszusetzen, um Fehlalarme zu vermeiden. Nach Abschluss des Ereignisses kann die ARP/AI-Analyse wieder aufgenommen werden.



[[pause-arpai]]
== ARP/AI pausieren

Bevor ein ungewöhnliches Arbeitslastereignis beginnt, kann es erforderlich sein, die ARP/AI-Analyse vorübergehend auszusetzen, um Fehlalarme zu vermeiden.

.Schritte
. Wählen Sie im System Manager *Storage* aus.
. Wählen Sie die Speichereinheiten aus, für die Sie ARP/AI pausieren möchten.
. Wählen Sie *Anti-Ransomware pausieren*.


.Ergebnis
Die ARP/AI-Analyse wird für die ausgewählten Speichereinheiten angehalten und Ihnen werden im System Manager keine verdächtigen Aktivitäten gemeldet, bis Sie ARP/AI wieder aufnehmen.



[[resume-arpai]]
== ARP/AI fortsetzen

Wenn Sie ARP/AI während einer ungewöhnlichen Arbeitslast pausieren, sollte es nach Abschluss der Arbeitslast wieder fortgesetzt werden, um Ihre Daten vor Ransomware-Angriffen zu schützen.

.Schritte
. Wählen Sie im System Manager *Storage* aus.
. Wählen Sie die Speichereinheiten aus, für die Sie ARP/AI fortsetzen möchten.
. Wählen Sie *Anti-Ransomware fortsetzen*.


.Ergebnis
Die Analyse potenzieller Ransomware-Angriffe wird fortgesetzt und verdächtige Aktivitäten werden Ihnen im System Manager gemeldet.
