---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Zeigen Sie Warnungen vor potenziellen Ransomware-Angriffen an und ergreifen Sie Maßnahmen im System Manager. 
---
= Auf ARP/AI-Warnungen auf ASA r2 Speichersystemen reagieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn der autonome Ransomware-Schutz mit künstlicher Intelligenz (ARP/KI) ungewöhnliche Aktivitäten auf einem oder mehreren Speichereinheiten Ihres ASA r2 Systems erkennt, zeigt System Manager eine Warnung im Dashboard an. Die Warnung sollte überprüft, die Aktivität verifiziert und bei Bedarf Maßnahmen zum Schutz der Daten ergriffen werden.

Wenn eine ARP/AI-Warnmeldung angezeigt wird, sollte mithilfe eines geeigneten Application Integrity Checkers die Daten auf dem Speichermedium überprüft werden, bevor Maßnahmen ergriffen werden. Die Überprüfung der Datenintegrität des Speichermediums ermöglicht die Feststellung, ob die Aktivität akzeptabel ist oder ob es sich um einen potenziellen Ransomware-Angriff handelt.

[cols="2,2"]
|===
| Wenn die abnormale Aktivität ... ist. | Dann tun Sie Folgendes ... 


| Akzeptabel | Markieren Sie die Aktivität als falsch-positiv. 


| Ein potenzieller Ransomware-Angriff | Markieren Sie die Aktivität als potenziellen Ransomware-Angriff. 


| Unbestimmt | Es sind keine sofortigen Maßnahmen erforderlich. Das Speichermedium sollte bis zu 7 Tage lang überwacht werden. Wenn das Speichermedium weiterhin normal funktioniert, ist die Aktivität als Fehlalarm zu kennzeichnen. Wenn das Speichermedium weiterhin ungewöhnliche Aktivitäten zeigt, ist die Aktivität als potenzieller Ransomware-Angriff zu kennzeichnen. 
|===
.Schritte
. Wählen Sie in System Manager *Dashboard* aus.
+
Wenn ARP/AI eine anormale Aktivität auf einer oder mehreren Speichereinheiten festgestellt hat, erscheint eine Meldung unter *Warnungen*.

. Wählen Sie die Warnmeldung aus.
. Wählen Sie unter *Ereignisübersicht* die Meldung *Warnungen* aus, die die Anzahl der Speichereinheiten mit abnormaler Aktivität angibt.
. Wählen Sie unter *Speichereinheiten mit ungewöhnlicher Aktivität* die Speichereinheit aus.
. Wählen Sie *Sicherheit*.
+
Bei ungewöhnlichen Aktivitäten auf dem Speichergerät wird unter *Anti-Ransomware* eine Meldung angezeigt.

. Wählen Sie *Aktion auswählen*.
. Wählen Sie *Als falsch-positiv markieren* oder *Als potenziellen Ransomware-Angriff markieren*.


.Was kommt als Nächstes?
Wenn Sie in Ihrer Speichereinheit Aktivitätsspitzen feststellen, entweder einmalige Spitzen oder eine Spitze, die für eine neue Normalität charakteristisch ist, sollten Sie diese als unbedenklich melden. Das manuelle Melden dieser Anstiege als unbedenklich trägt dazu bei, die Genauigkeit der Bedrohungsbewertungen von ARP zu verbessern. Weitere Informationen link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["Bekannte ARP/AI-Spitzen melden"^].
