---
sidebar: sidebar 
permalink: learn-more/additional-supported-ontap-features.html 
keywords: asa r2, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, cli, command line interface, clustered external key servers, external key management, encryption at rest, administrator access management, client authentication, oauth 2.0, saml authentication, fips compliance, link aggregation groups, iscsi, fibre channel, fc, nvme, nvme unmap, hole punch, deallocation, system manager 
summary: Da auf ASA r2-Systemen eine optimierte Version von ONTAP ausgeführt wird, werden viele allgemeine ONTAP Aufgaben und System Manager-Funktionen auf ASA r2-Systemen auf die gleiche Weise ausgeführt wie auf anderen ONTAP Systemen. 
---
= Allgemeine ONTAP -Funktionen, die auf ASA R2-Systemen unterstützt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Da auf ASA r2-Systemen eine optimierte Version von ONTAP ausgeführt wird, werden viele allgemeine ONTAP Aufgaben und System Manager-Funktionen auf ASA r2-Systemen auf die gleiche Weise ausgeführt wie auf anderen ONTAP Systemen.

Weitere Informationen zu allgemeinen Features und Funktionen finden Sie in der folgenden ONTAP Dokumentation.



[[data-protection]]
== Datensicherung

Erfahren Sie mehr über die gängigen Datenschutzfunktionen, die auf ASA r2-Systemen unterstützt werden.



[[clustered-external-key-servers]]
=== Clustered externe Schlüsselserver

Sie können die Konnektivität zu geclusterten externen Schlüsselverwaltungsservern auf einer Speicher-VM konfigurieren. Mit geclusterten Schlüsselservern können Sie primäre und sekundäre Schlüsselserver auf einer Speicher-VM festlegen. Bei der Registrierung von Schlüsseln versucht ONTAP zunächst, auf einen primären Schlüsselserver zuzugreifen, bevor es nacheinander versucht, auf sekundäre Server zuzugreifen, bis der Vorgang erfolgreich abgeschlossen ist. Dadurch wird eine Duplizierung der Schlüssel verhindert.

link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-cluster-key-server-task.html["Lernen Sie, wie Sie gruppierte externe Schlüsselserver konfigurieren."^].



[[external-key-management-for-encryption-at-rest]]
=== Externes Schlüsselmanagement für die Verschlüsselung ruhender Daten

Sie können einen oder mehrere KMIP-Server verwenden, um die Schlüssel zu sichern, die der Cluster für den Zugriff auf verschlüsselte Daten verwendet.

* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-hw-task.html["Externe Schlüsselverwaltung aktivieren"^].
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-nve-task.html["Externe Schlüsselverwaltung (NVE) aktivieren"^] .




[[data-security]]
== Datensicherheit

Erfahren Sie mehr über gängige Datensicherheitsfunktionen, die auf ASA r2-Systemen unterstützt werden.



[[administrator-access-management]]
=== Administratorzugriffsverwaltung

Die einem Administrator zugewiesene Rolle bestimmt, welche Funktionen der Administrator ausführen kann.  System Manager stellt vordefinierte Rollen für Cluster-Administratoren und Storage-VM-Administratoren bereit.  Sie weisen die Rolle bei der Erstellung des Administratorkontos zu, oder Sie können später eine andere Rolle zuweisen.

* link:https://docs.netapp.com/us-en/ontap/task_security_administrator_access.html["Lernen Sie, den Administratorzugriff mit System Manager zu verwalten."^].




[[client-authentication-and-authorization]]
=== Client-Authentifizierung und -Autorisierung

ONTAP verwendet Standardmethoden, um den Zugriff von Clients und Administratoren auf den Speicher zu sichern und vor Viren zu schützen.  Für die Verschlüsselung ruhender Daten und für die WORM-Speicherung stehen fortschrittliche Technologien zur Verfügung.  ONTAP authentifiziert einen Clientrechner und einen Benutzer, indem es deren Identität mit einer vertrauenswürdigen Quelle verifiziert.  ONTAP autorisiert einen Benutzer zum Zugriff auf eine Datei oder ein Verzeichnis, indem es die Anmeldeinformationen des Benutzers mit den für die Datei oder das Verzeichnis konfigurierten Berechtigungen vergleicht.

link:https://docs.netapp.com/us-en/ontap/concepts/client-access-storage-concept.html["Erfahren Sie mehr über Clientauthentifizierung und -autorisierung"^] .



[[oauth-2-0-authentication]]
=== OAuth 2.0-Authentifizierung

Sie können das Open Authorization (OAuth 2.0) Framework verwenden, um den Zugriff auf Ihre ONTAP Cluster zu steuern.  OAuth 2.0 beschränkt und kontrolliert den Zugriff auf geschützte Ressourcen mithilfe signierter Zugriffstoken.

link:https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["Erfahren Sie mehr über die OAuth 2.0-Authentifizierung"^] .



[[saml-authentication-and-administrator-access]]
=== SAML-Authentifizierung und Administratorzugriff

Sie können die Security Assertion Markup Language (SAML)-Authentifizierung für Webdienste konfigurieren und aktivieren.  SAML authentifiziert Benutzer über einen externen Identitätsanbieter (IdP) anstelle von Verzeichnisdienstanbietern wie Active Directory und LDAP.

link:https://docs.netapp.com/us-en/ontap/system-admin/configure-saml-authentication-task.html["Erfahren Sie, wie Sie die SAML-Authentifizierung konfigurieren"^] .



[[tls-hardware-offload]]
=== TLS-Hardware-Offload

Sie können die Transport Layer Security (TLS)-Verschlüsselung und -Entschlüsselung für Ihren gesamten Cluster auf unterstützte Ethernet-Karten auslagern. Dies reduziert die CPU-Auslastung und verbessert die Leistung von Systemen, die TLS verwenden.

link:https://docs.netapp.com/us-en/ontap/networking/configure-tls-offload.html["Lernen Sie, die Hardware-Offload-Funktion für TLS zu konfigurieren."^].



[[networking]]
== Vernetzung

Erfahren Sie mehr über die gängigen Netzwerkfunktionen, die auf ASA r2-Systemen unterstützt werden.



[[fips-compliance]]
=== FIPS-Konformität

ONTAP erfüllt die Anforderungen des Federal Information Processing Standards (FIPS) 140-2 für alle SSL-Verbindungen.  Sie können den SSL-FIPS-Modus ein- und ausschalten, SSL-Protokolle global festlegen und schwache Verschlüsselungsverfahren wie RC4 innerhalb von ONTAP deaktivieren.

Ab ONTAP 9.18.1 werden Postquanten-Computing-Kryptographiealgorithmen für SSL unterstützt.  Diese Algorithmen bieten zusätzlichen Schutz vor potenziellen zukünftigen Quantencomputerangriffen und sind auch dann verfügbar, wenn der SSL-FIPS-Modus deaktiviert ist.

* link:https://docs.netapp.com/us-en/ontap/networking/configure_network_security_using_federal_information_processing_standards_fips.html["Lernen Sie, FIPS für alle SSL-Verbindungen zu konfigurieren."^].




[[link-aggregation-groups-lags]]
=== Link-Aggregationsgruppen (LAGs)

Eine Schnittstellengruppe, auch Link Aggregation Group (LAG) genannt, entsteht durch die Kombination von zwei oder mehr physischen Ports auf demselben Knoten zu einem einzigen logischen Port.  Der logische Port bietet erhöhte Ausfallsicherheit, erhöhte Verfügbarkeit und Lastverteilung.

link:https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html["Erfahren Sie mehr über Link-Aggregationsgruppen"^].



[[performance]]
== Performance

Erfahren Sie mehr über die gängigen Leistungsmerkmale, die auf ASA r2-Systemen unterstützt werden.



[[modify-default-settings-that-control-automatic-qos-throughput-ceiling-increases]]
=== Ändern Sie die Standardeinstellungen, die die automatische Erhöhung des QoS-Durchsatzlimits steuern

Adaptive und nicht-adaptive QoS-Richtliniengruppen werden standardmäßig automatisch aktiviert, um die Durchsatzobergrenze einer Arbeitslast für eine Dauer von 1 Sekunde um 50 % zu erhöhen, um kurzfristigen Anforderungen an eine höhere Leistung zu entsprechen. Ab ONTAP 9.19.1 können Sie diese Standardeinstellungen ändern. In ONTAP 9.18.1 und früher können diese Einstellungen nicht geändert werden.

link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Erfahren Sie mehr über QoS-Durchsatzgrenzen"^].



[[ipspace-tcp-performance]]
=== IPspace TCP-Leistung

Ab ONTAP 9.19.1 verbessert ONTAP die TCP-Datentransferleistung über verlustbehaftete WAN-Verbindungen mit hoher Latenz durch die Integration von zwei Verlustwiederherstellungsfunktionen, PRR und RACK, in den ONTAP TCP-Stack. PRR eignet sich für alle Netzwerke und ist standardmäßig aktiviert. RACK eignet sich für überlastete Netzwerke mit Verbindungsgeschwindigkeiten von etwa 25 Gigabit/Sekunde und ist standardmäßig deaktiviert.

link:https://docs.netapp.com/us-en/ontap/networking/improve-tcp-wan-performance.html["Weitere Informationen zur Verbesserung der TCP WAN-Leistung mit PRR und RACK"^].



[[san-configuration]]
== SAN-Konfiguration

Ein storage area network (SAN) besteht aus einer Speicherlösung, die über ein SAN-Transportprotokoll wie iSCSI oder FC mit Hosts verbunden ist. Sie können Ihr SAN so konfigurieren, dass Ihre Speicherlösung über einen oder mehrere Switches mit Ihren Hosts verbunden wird. Wenn Sie iSCSI verwenden, können Sie Ihr SAN auch so konfigurieren, dass Ihre Speicherlösung direkt mit Ihrem Host verbunden wird, ohne einen Switch zu verwenden.



[[san-direct-attachment]]
=== SAN-Direktanbindung

Ab ONTAP 9.19.1 ist kein FC-Switch mehr erforderlich, um Verbindungen zwischen FC- und FC-NVMe-Hosts und ONTAP Storage herzustellen. Hosts können direkt an die FC-Adapterports von ASA r2-Systemen angeschlossen werden. Diese Direktanschlussmöglichkeit ist besonders in Remote-Sites und hybriden Umgebungen von Vorteil, wo Einfachheit im Vordergrund steht.

* link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html#direct-attach-fc-and-fc-nvme-configurations["Erfahren Sie mehr über die direkte SAN-Anbindung"^].




[[san-protocols]]
== SAN-Protokolle

ASA r2-Systeme unterstützen alle SAN-Protokolle (iSCSI, FC, NVMe/FC, NVMe/TCP).

* link:https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html["Erfahren Sie mehr über das iSCSI-Protokoll."^].
* link:https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Erfahren Sie mehr über das Fibre Channel (FC)-Protokoll."^].
* link:https://docs.netapp.com/us-en/ontap/concept_nvme_provision_overview.html["Erfahren Sie mehr über das NVMe-Protokoll."^].
+
** link:https://docs.netapp.com/us-en/ontap/san-admin/nvme-copy-offload.html["Lernen Sie, NVMe Copy Offload zu konfigurieren"^].
+
Ab ONTAP 9.18.1 wird NVMe Copy Offload unterstützt.  NVMe Copy Offload ermöglicht es einem NVMe-Host, Kopiervorgänge von seiner CPU auf die CPU des ONTAP -Speichercontrollers auszulagern.  Der Host kann Daten von einem NVMe-Namespace in einen anderen kopieren und dabei seine CPU-Ressourcen für Anwendungsworkloads reservieren.

** link:https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html["Erfahren Sie mehr über die Speicherplatzzuweisung (Unmap) für NVMe."^].
+
Ab ONTAP 9.16.1 ist die Speicherplatzfreigabe (auch „Hole Punching“ und „Unmap“ genannt) für NVMe-Namespaces standardmäßig aktiviert. Durch die Freigabe von Speicherplatz kann ein Host die Zuweisung nicht verwendeter Blöcke aus Namespaces aufheben, um Speicherplatz freizugeben.







[[storage-efficiency]]
== Storage-Effizienz

Die Speichereffizienz ist das Maß dafür, wie effektiv ein Speichersystem den verfügbaren Platz nutzt, indem es die Speicherressourcen optimiert, verschwendeten Platz minimiert und den physischen Platzbedarf der geschriebenen Daten reduziert.

ONTAP bietet verschiedene Speichereffizienztechnologien, die Ihnen helfen können, die Speichernutzung zu optimieren und Kosten zu senken.

link:https://docs.netapp.com/us-en/ontap/concepts/storage-efficiency-overview.html["Erfahren Sie mehr über ONTAP-Speichereffizienztechnologien"].



[[global-deduplication]]
=== Globale Deduplizierung

Ab ONTAP 9.19.1 erweitert die link:https://docs.netapp.com/us-en/ontap/concepts/deduplication-concept.html["bestehende ONTAP Deduplizierungsspeichereinsparungen"^] globale Deduplizierung die Speichereinheitsebene auf die gesamte Storage Availability Zone (SAZ). Durch die Eliminierung doppelter Datenblöcke über alle Speichereinheiten der SAZ hinweg lässt sich die Speichereffizienz deutlich steigern und die Gesamtbetriebskosten senken. Die globale Deduplizierung benötigt keine Funktionslizenz, ist standardmäßig aktiviert, integriert sich nahtlos in bestehende Technologien zur Speichereffizienz und arbeitet transparent mit minimalen Leistungseinbußen und ohne administrative Konfiguration.



[[system-manager]]
== System Manager

Im System Manager können Sie nach verschiedenen Aktionen, Objekten und Informationsthemen suchen.  Sie können auch in den Tabellendaten nach bestimmten Einträgen suchen.

link:https://docs.netapp.com/us-en/ontap/task_admin_search_filter_sort.html["Lernen Sie, Informationen im System Manager zu suchen, zu filtern und zu sortieren."^].
