---
sidebar: sidebar 
permalink: learn-more/cli-support.html 
keywords: asa r2, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, cli, comand line interface 
summary: 'Bestimmte ONTAP-Befehle werden auf ASA r2-Systemen (ASA A1K, ASA 90, ASA 70, ASA A50, ASA A30, ASA A20, ASA C30) nicht unterstützt.' 
---
= ONTAP CLI-Unterstützung für ASA r2 Storage-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 Systeme verwenden Speicherverfügbarkeitszonen anstelle von Aggregaten, daher werden einige ONTAP CLI-Befehle und Parameter nicht unterstützt. Die CLI kann ebenfalls zur Einrichtung eines Clusters genutzt werden, wenn dies dem System Manager vorgezogen wird.

Aufgrund dieses vereinfachten Ansatzes zur Speicherverwaltung  `storage aggregate` Befehle werden auf ASA r2-Systemen nicht unterstützt. Unterstützung für bestimmte  `lun` ,  `storage` Und  `volume` Befehle und Parameter sind ebenfalls begrenzt.

Sofern nicht als nicht unterstützt aufgeführt, sind alle anderen Befehle in der link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP-Befehlsreferenz"] für ASA r2-Systeme unterstützt.

Die folgenden Befehle und Befehlssätze sind auf ASA r2 nicht unterstützt:

.Nicht unterstützte <code>-</code>-Befehle
[%collapsible]
====
* `lun copy`
* `lun geometry`
* `lun maxsize`
* `lun move`
* `lun move-in-volume`
+

NOTE: Der  `lun move-in-volume` Befehl wird ersetzt durch den  `lun rename` und die  `vserver nvme namespace rename` Befehle.

* `lun transition`


====
.Nicht unterstützte <code>-</code>-Befehle
[%collapsible]
====
* `storage failover show-takeover`
* `storage failover show-giveback`
* `storage disk assign`
* `storage disk partition`
* `storage disk reassign`


====
.Nicht unterstützte <code>-</code>-Befehlssätze
[%collapsible]
====
* `volume activity-tracking`
* `volume analytics`
* `volume conversion`
* `volume file`
* `volume flexcache`
* `volume flexgroup`
* `volume inode-upgrade`
* `volume object-store`
* `volume qtree`
* `volume quota`
* `volume reallocation`
* `volume rebalance`
* `volume recovery-queue`
* `volume schedule-style`


====
.Nicht unterstützte <code>-</code>-Befehle und -Parameter
[%collapsible]
====
* `volume autosize`
* `volume create`
* `volume delete`
* `volume expand`
* `volume modify`
+
Der  `volume modify` Der Befehl ist nicht verfügbar, wenn er in Verbindung mit den folgenden Parametern verwendet wird:

+
** `-anti-ransomware-state`
** `-autosize`
** `-autosize-mode`
** `-autosize-shrik-threshold-percent`
** `-autosize-reset`
** `-group`
** `-is-cloud-write-enabled`
** `-is-space-enforcement-logical`
** `-max-autosize`
** `-min-autosize`
** `-offline`
** `-online`
** `-percent-snapshot-space`
** `-qos*`
** `-size`
** `-snapshot-policy`
** `-space-guarantee`
** `-space-mgmt-try-first`
** `-state`
** `-tiering-policy`
** `-tiering-minimum-cooling-days`
** `-user`
** `-unix-permisions`
** `-vserver-dr-protection`


* `volume make-vsroot`
* `volume mount`
* `volume move`
* `volume offline`
* `volume rehost`
* `volume rename`
* `volume restrict`
* `volume transition-prepare-to-downgrade`
* `volume unmount`


====
.Nicht unterstützte <code>-Befehle für die Clitzebaus-</code>
[%collapsible]
====
* `volume clone create`
* `volume clone split`


====
.Nicht unterstützte <code>-SnapLock </code>-Befehle
[%collapsible]
====
* `volume snaplock modify`


====
.Nicht unterstützte <code>-Befehle für den </code>-Ausschnapper
[%collapsible]
====
* `volume snapshot`
* `volume snapshot autodelete modify`
* `volume snapshot policy modify`


====


[[set-up-an-ontap-asa-r2-cluster-using-the-cli]]
== Richten Sie einen ONTAP ASA r2-Cluster mithilfe der CLI ein

Es wird empfohlen, dass Sie link:../install-setup/initialize-ontap-cluster.html["Richten Sie den ONTAP ASA r2-Cluster mit System Manager ein"]. System Manager bietet einen schnellen und einfachen geführten Workflow, um Ihr Cluster in Betrieb zu nehmen. Wenn Sie jedoch daran gewöhnt sind, mit ONTAP Befehlen zu arbeiten, kann optional die ONTAP Befehlszeilenschnittstelle (CLI) für die Cluster-Einrichtung verwendet werden. Die Einrichtung des Clusters mit der CLI bietet keine zusätzlichen Optionen oder Vorteile gegenüber System Manager.

Während der Cluster-Einrichtung erstellt ONTAP Ihre standardmäßige Datenspeicher-VM, erstellt eine erste Speichereinheit und erkennt automatisch Ihre Daten-LIFs. Optional kann das Domain Name System (DNS) zur Auflösung von Hostnamen aktiviert werden, der Cluster für die Verwendung des Network Time Protocol (NTP) zur Zeitsynchronisierung konfiguriert werden und die Verschlüsselung von Daten im Ruhezustand aktiviert werden.

.Bevor Sie beginnen
Stellen Sie die folgenden Informationen zusammen:

* Cluster-Management-IP-Adresse
+
Die Cluster-Management-IP-Adresse ist eine eindeutige IPv4-Adresse für die Cluster-Managementoberfläche, die vom Cluster-Administrator für den Zugriff auf die Admin-Storage-VM und das Management des Clusters verwendet wird. Sie können diese IP-Adresse vom Administrator beziehen, der für das Zuweisen von IP-Adressen in Ihrem Unternehmen verantwortlich ist.

* Netzwerk-Subnetzmaske
+
Während der Cluster-Einrichtung empfiehlt ONTAP eine Reihe von Netzwerkschnittstellen, die für die jeweilige Konfiguration geeignet sind. Sie können die Empfehlung bei Bedarf anpassen.

* IP-Adresse des Netzwerk-Gateways
* Partner-Node-IP-Adresse
* DNS-Domain-Namen
* IP-Adressen des DNS-Namensservers
* IP-Adressen des NTP-Servers
* Daten-Subnetzmaske


.Schritte
. Schalten Sie beide Nodes des HA-Paars ein.
. Zeigt die im lokalen Netzwerk erkannten Nodes an:
+
[source, cli]
----
system node show-discovered -is-in-cluster false
----
. Starten Sie den Cluster-Einrichtungsassistenten:
+
[source, cli]
----
cluster setup
----
. Bestätigen Sie die AutoSupport-Anweisung.
. Geben Sie Werte für den Port der Node-Managementoberfläche, die IP-Adresse, die Netmask und das Standard-Gateway ein.
. Drücken Sie *Enter*, um die Einrichtung über die Befehlszeilenschnittstelle fortzusetzen; geben Sie dann *create* ein, um einen neuen Cluster zu erstellen.
. Übernehmen Sie die Systemstandards oder geben Sie Ihre eigenen Werte ein.
. Nachdem das Setup auf dem ersten Node abgeschlossen ist, melden Sie sich beim Cluster an.
. Vergewissern Sie sich, dass das Cluster aktiv ist und der erste Node ordnungsgemäß funktioniert:
+
[source, cli]
----
system node show-discovered
----
. Fügen Sie dem Cluster den zweiten Node hinzu:
+
[source, cli]
----
cluster add-node -cluster-ip <partner_node_ip_address>
----
. Optional können Sie die Systemzeit über das Cluster hinweg synchronisieren
+
[cols="1h, 1"]
|===


| Synchronisierung ohne symmetrische Authentifizierung  a| 
[source, cli]
----
cluster time-service ntp server create -server <server_name>
----


| Synchronisierung mit symmetrischer Authentifizierung  a| 
[source, cli]
----
cluster time-service ntp server create -server <server_ip_address> -key-id <key_id>
----
|===
+
.. Vergewissern Sie sich, dass das Cluster einem NTP-Server zugeordnet ist:
+
[source, cli]
----
Cluster time-service ntp show
----


. Optional können link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]Sie die Konfiguration herunterladen und ausführen.


.Was kommt als Nächstes?
Sie können link:../install-setup/set-up-data-access.html["Richten Sie den Datenzugriff ein"]Ihre SAN-Clients auf Ihr System übertragen.
