---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a70, asa a90 
summary: ASA Systeme bieten Hardware-Support, der für reine SAN-Lösungen optimiert ist. ASA r2 Systeme ermöglichen die Optimierung von Hardware und Software. 
searchtitle: Vergleichen Sie ASA r2 Systeme mit anderen ONTAP Systemen 
---
= Vergleichen Sie ASA r2 Systeme mit anderen ONTAP Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung für reine SAN-Umgebungen, die auf All-Flash-Plattformen basieren. ASA r2 Systeme unterscheiden sich bei der Implementierung ihrer Storage-Ebene, unterstützter Protokolle und ONTAP Persönlichkeit von anderen ONTAP Systemen (ASA, AFF und FAS).

Auf einem ASA r2 System wird die ONTAP Software optimiert, um wichtige SAN-Funktionen zu unterstützen und gleichzeitig die Sichtbarkeit und Verfügbarkeit von nicht-SAN-bezogenen Funktionen zu beschränken. Beispielsweise zeigt System Manager, der auf einem ASA r2 System ausgeführt wird, keine Optionen zum Erstellen von Home Directorys für NAS-Clients an. Diese optimierte Version von ONTAP wird als _ASA r2 Personality_ bezeichnet. ONTAP, die auf allen anderen ONTAP Systemen (ASA, AFF, FAS) ausgeführt werden, wird als „_Unified ONTAP Personality_“ bezeichnet. Die Unterschiede zwischen den ONTAP-Persönlichkeiten werden in der ONTAP-Befehlsreferenz (man-Pages), in der REST-API-Spezifikation und ggf. in EMS-Meldungen erwähnt.

Sie können die Persönlichkeit Ihres ONTAP-Speichers vom System Manager oder von der ONTAP-CLI überprüfen.

* Wählen Sie im Menü System Manager *Cluster > Übersicht*.
* Geben Sie über die CLI Folgendes ein: `san config show`


Die Persönlichkeit Ihres ONTAP Storage-Systems kann nicht geändert werden.

Die Storage-Ebene für ONTAP Systeme, auf denen die Unified ONTAP Personality ausgeführt wird, verwendet Aggregate als Storage-Basiseinheit. Ein Aggregat besitzt einen bestimmten Satz der in einem Storage-System verfügbaren Festplatten. Das Aggregat weist den Speicherplatz auf den Festplatten zu, denen es Volumes für LUNs und Namespaces besitzt. Ein einheitlicher ONTAP-Benutzer kann über die Befehlszeilenschnittstelle (CLI) Aggregate, Volumes, LUNs und Namespaces erstellen und ändern.

Die Storage-Ebene in ASA r2 Systemen verwendet anstelle von Aggregaten eine Storage-Verfügbarkeitszone. Eine Storage-Verfügbarkeitszone ist ein gemeinsamer Speicherpool, der Zugriff auf alle verfügbaren Festplatten im Speichersystem hat. Die Storage-Verfügbarkeitszone ist für beide Nodes in einem ASA r2 HA-Paar sichtbar. Bei der Erstellung einer Storage-Einheit (entweder auf Basis einer LUN oder eines NVMe Namespace) erstellt ONTAP automatisch ein Volume mit einer Storage Virtual Machine (VM) in der Storage-Verfügbarkeitszone, um die Storage-Einheit zu beherbergen. Aufgrund dieses automatisierten und vereinfachten Ansatzes für das Storage-Management sind bestimmte System Manager Optionen, ONTAP Befehle und REST-API-Endpunkte nicht verfügbar oder werden von einem ASA r2 System nur eingeschränkt genutzt. Da beispielsweise `volume create` die Erstellung und Verwaltung von Volumes für ASA r2-Systeme automatisiert ist, wird das Menü *Volumes* im System-Manager nicht angezeigt und der Befehl wird nicht unterstützt.

ASA r2 Storage wird wie folgt mit anderen ONTAP Storage-Systemen verglichen:

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
*ONTAP-Persönlichkeit*
| ASA r2 | ASA | Virtualisierung | Virtualisierung 


 a| 
*Unterstützung für SAN-Protokolle*
| Ja. | Ja. | Ja. | Ja. 


 a| 
*Unterstützung des NAS-Protokolls*
| Nein | Nein | Ja. | Ja. 


 a| 
*Unterstützung der Speicherschicht*
| Zone der Storage-Verfügbarkeit | Aggregate | Aggregate | Aggregate 
|===
Die folgenden ASA-Plattformen werden als ASA r2-Systeme klassifiziert:

* ASA A1K
* ASA A70
* ASA A90


.Finden Sie weitere Informationen
* Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAP Hardwaresysteme"^].
* Siehe vollständige Konfigurationsunterstützung und -Einschränkungen für ASA- und ASA r2-Systeme in link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Erfahren Sie mehr über die link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].




== Zusammenfassung der ASA r2-Systemunterschiede

Die Hauptunterschiede zwischen ASA r2 Systemen und FAS, AFF und ASA Systemen, die für die ONTAP Befehlszeilenschnittstelle (CLI) und REST API relevant sind, werden im Folgenden beschrieben.

.Standardmäßige SVM-Erstellung mit Protokolldiensten
Neue Cluster enthalten automatisch eine Standard-Daten-SVM, bei der die SAN-Protokolle aktiviert sind. IP-Daten-LIFs unterstützen iSCSI- und NVMe/TCP-Protokolle und verwenden `default-data-blocks` standardmäßig die Servicerichtlinie.

.Automatische Volume-Erstellung
Durch Erstellen einer Storage-Einheit (LUN oder Namespace) wird automatisch ein Volume aus der Storage-Verfügbarkeitszone erstellt. Dies führt zu einem vereinfachten und gemeinsamen Namespace. Durch Löschen einer Speichereinheit wird das zugeordnete Volume automatisch gelöscht.

.Änderungen an Thin Provisioning und Thick Provisioning
Storage-Einheiten für werden auf ASA r2-Storage-Systemen immer über Thin Provisioning bereitgestellt. Thick Provisioning wird nicht unterstützt.
