---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: ASA Systeme bieten Hardware-Support, der für reine SAN-Lösungen optimiert ist. ASA r2 Systeme ermöglichen die Optimierung von Hardware und Software. 
searchtitle: Vergleichen Sie ASA r2 Systeme mit anderen ONTAP Systemen 
---
= Vergleichen Sie ASA r2 Systeme mit anderen ONTAP Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2-Systeme bieten eine Hardware- und Softwarelösung für reine SAN-Umgebungen, die auf All-Flash-Lösungen basieren. ASA R2-Systeme unterscheiden sich von anderen ONTAP Systemen (ASA, AFF und FAS) in der Implementierung der ONTAP Persönlichkeit, der Speicherschicht und der unterstützten Protokolle.

Folgende Systeme werden als ASA r2-Systeme klassifiziert:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== Persönlichkeitsunterschiede

Auf einem ASA r2 System wird die ONTAP Software optimiert, um wichtige SAN-Funktionen zu unterstützen und gleichzeitig die Sichtbarkeit und Verfügbarkeit von nicht-SAN-bezogenen Funktionen zu beschränken. Beispielsweise zeigt System Manager, der auf einem ASA r2 System ausgeführt wird, keine Optionen zum Erstellen von Home Directorys für NAS-Clients an. Diese optimierte Version von ONTAP wird als _ASA r2 Personality_ bezeichnet. ONTAP auf ASA Systemen wird als _ASA ONTAP Personality_ identifiziert. ONTAP auf AFF und FAS ONTAP Systemen wird als „_Unified ONTAP Personality_“ bezeichnet. Die Unterschiede zwischen den ONTAP-Persönlichkeiten werden in der ONTAP-Befehlsreferenz (man-Pages), in der REST-API-Spezifikation und ggf. in EMS-Meldungen erwähnt.

Sie können die Persönlichkeit Ihres ONTAP-Speichers vom System Manager oder von der ONTAP-CLI überprüfen.

* Wählen Sie im Menü System Manager *Cluster > Übersicht*.
* Geben Sie in der CLI Folgendes ein: `system node show -personality -is-disaggregated`


Bei ASA r2-Systemen ist die _Persönlichkeit_ _ASA r2_ und der Status von _is-disaggregated_ ist _true_.

Die Persönlichkeit Ihres ONTAP Storage-Systems kann nicht geändert werden.



== Unterschiede der Speicherebenen

ASA r2-Systeme verwenden eine vereinfachte Speicherschicht, die sich von der Speicherschicht unterscheidet, die von FAS, AFF und ASA Systemen verwendet wird.

.FAS, AFF und ASA -Systeme
Die Speicherschicht für FAS -, AFF- und ASA -Systeme verwendet Aggregate als Basisspeichereinheit. Ein Aggregat besitzt einen bestimmten Satz der im Speichersystem verfügbaren Festplatten. Das Aggregat weist den Speicherplatz auf den zugehörigen Festplatten Volumes für LUNs und Namespaces zu. Mit diesen Systemen können ONTAP Benutzer Aggregate, Volumes, LUNs und Namespaces erstellen und ändern.

.ASA r2-Systeme
Anstelle von Aggregaten verwendet die Speicherebene in ASA r2-Systemen Speicherverfügbarkeitszonen. Eine Speicherverfügbarkeitszone ist ein gemeinsamer Speicherpool, der beiden Knoten eines HA-Paares zur Verfügung steht. Beide Knoten im HA-Paar haben Zugriff auf alle verfügbaren Festplatten in ihrer gemeinsamen Speicherverfügbarkeitszone. Beispielsweise gibt es in einem ASA r2-System- ONTAP Cluster mit zwei Knoten eine Speicherverfügbarkeitszone, auf die beide Knoten im Cluster zugreifen können. In einem ASA r2-System- ONTAP Cluster mit vier Knoten gibt es zwei Speicherverfügbarkeitszonen. Jedes HA-Paar im Cluster hat Zugriff auf eine der Speicherverfügbarkeitszonen.

Beim Erstellen einer Speichereinheit (basierend auf einem LUN- oder NVMe-Namespace) erstellt ONTAP automatisch ein Volume in der entsprechenden Storage Availability Zone, um die Speichereinheit unterzubringen. Das neu erstellte Volume wird automatisch in der Storage Availability Zone platziert, um optimale Leistung und eine ausgewogene Kapazitätsauslastung zu gewährleisten. Die Kapazitätsauslastung innerhalb der Speicherverfügbarkeitszone wird auf Basis Ihrer ONTAP-Version ausgeglichen. link:administer/space-balancing.html["Erfahren Sie mehr über Kapazitätsausgleich in einem ASA r2-Cluster"^].



== Zusammenfassung der Unterschiede im ASA r2-System

ASA r2-Systeme unterscheiden sich von FAS, AFF und ASA -Systemen in folgenden Punkten:

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
*ONTAP-Persönlichkeit*
| ASA r2 | ASA | Virtualisierung | Virtualisierung 


 a| 
*Unterstützung für SAN-Protokolle*
| Ja. | Ja. | Ja. | Ja. 


 a| 
*Unterstützung des NAS-Protokolls*
| Nein | Nein | Ja. | Ja. 


 a| 
*Unterstützung der Speicherschicht*
| Zone der Storage-Verfügbarkeit | Aggregate | Aggregate | Aggregate 
|===
Aufgrund dieses automatisierten und vereinfachten Ansatzes zur Speicherverwaltung sind bestimmte System Manager-Optionen, ONTAP -Befehle und REST-API-Endpunkte auf einem ASA r2-System nicht verfügbar oder nur eingeschränkt nutzbar. Da beispielsweise die Volume-Erstellung und -Verwaltung für ASA r2-Systeme automatisiert ist, wird das Menü *Volumes* im System Manager nicht angezeigt und die  `volume create` Befehl wird nicht unterstützt. link:cli-support.html["Erfahren Sie mehr über nicht unterstützte ASA R2-Befehle"] .

Die Hauptunterschiede zwischen ASA r2 Systemen und FAS, AFF und ASA Systemen, die für die ONTAP Befehlszeilenschnittstelle (CLI) und REST API relevant sind, werden im Folgenden beschrieben.

.Standardmäßige Erstellung von Speicher-VMs mit Protokolldiensten
Neue Cluster enthalten automatisch eine virtuelle Standard-Datenspeichermaschine (VM) mit aktivierten SAN-Protokollen.  IP-Daten-LIFs unterstützen die iSCSI- und NVMe/TCP-Protokolle und verwenden die `default-data-blocks` Standardmäßig gilt die Servicerichtlinie.

.Automatische Volume-Erstellung
Durch Erstellen einer Storage-Einheit (LUN oder Namespace) wird automatisch ein Volume aus der Storage-Verfügbarkeitszone erstellt. Dies führt zu einem vereinfachten und gemeinsamen Namespace. Durch Löschen einer Speichereinheit wird das zugeordnete Volume automatisch gelöscht.

.Änderungen an Thin Provisioning und Thick Provisioning
Storage-Einheiten werden auf ASA r2-Storage-Systemen immer über Thin Provisioning bereitgestellt. Thick Provisioning wird nicht unterstützt.

.Änderungen an der Datenkomprimierung
Temperaturempfindliche Storage-Effizienz wird auf ASA r2-Systemen nicht angewendet. Auf ASA r2-Systemen basiert die Komprimierung nicht auf _Hot_-Daten (auf die häufig zugegriffen wird) oder _Cold_-Daten (auf die selten zugegriffen wird). Die Komprimierung beginnt, ohne auf Daten zu warten, die kalt werden.

.Finden Sie weitere Informationen
* Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAP Hardwaresysteme"^].
* Siehe vollständige Konfigurationsunterstützung und -Einschränkungen für ASA- und ASA r2-Systeme in link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Erfahren Sie mehr über die link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].

