---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: ASA r2 Systeme bieten zwar eine breite Unterstützung für SAN-Lösungen, bestimmte ONTAP Softwarefunktionen werden jedoch nicht unterstützt. 
---
= Unterstützung und Einschränkungen der ONTAP Software für ASA r2 Storage-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 Systeme unterstützen eine breite Palette von SAN-Funktionen, aber einige ONTAP Softwarefunktionen werden nicht unterstützt.

.ASA r2-Systeme unterstützen Folgendes nicht:
* FabricPool
* Thick Provisioning für LUNs
* MetroCluster
* NetApp Aggregate Encryption (NAE)
* Objektprotokolle
* ONTAP S3 SnapMirror und S3-APIs
* SnapLock
+
SnapLock Compliance- und Enterprise-Modus werden auf primären Clustern in SAN-Umgebungen nicht unterstützt. SnapLock für SnapVault wird auf sekundären Clustern unterstützt.

* Die SnapMirror Replikation wird auf ASA r2-Systemen mit folgenden Einschränkungen unterstützt:
+
** Die synchrone Replikation von SnapMirror wird nicht unterstützt.
** SnapMirror asynchrone Replizierung wird nur zwischen zwei ASA r2 Systemen unterstützt. SnapMirror asynchrone Replizierung wird nicht zwischen einem ASA r2 System und einem ASA, AFF oder FAS System oder der Cloud unterstützt.
+
Erfahren Sie mehr überlink:../data-protection/pre-defined-protection-policies.html["SnapMirror Replikationsrichtlinien werden auf ASA r2-Systemen unterstützt"] .

** SnapMirror Active Sync wird nur zwischen zwei ASA r2-Systemen unterstützt.
+
Erfahren Sie mehr überlink:../data-protection/snapmirror-active-sync.html["SnapMirror Active Sync auf ASA r2-Systemen"] .





.ASA r2-Systeme unterstützen Folgendes:
* Dual-Layer-Verschlüsselung
+
ASA r2-Systeme unterstützen Hardwareverschlüsselung mittels selbstverschlüsselnder Laufwerke (SEDs) und Softwareverschlüsselung mittels NetApp Volume Encryption (NVE) Technologie. link:../secure-data/encrypt-data-at-rest.html["Erfahren Sie, wie Sie eine zweischichtige Verschlüsselung anwenden"] für Daten auf Ihrem ASA r2-System.



.Finden Sie weitere Informationen
* link:https://hwu.netapp.com/["NetApp Hardware Universe"^]Weitere Informationen zur Unterstützung und zu Einschränkungen der ASA r2-Hardware finden Sie im.

