---
sidebar: sidebar 
permalink: manage-data/create-host-groups.html 
keywords: create host group, map storage units, host access, asa r2 
summary: Erstellen Sie Hostgruppen, um Hosts Zugriff auf Speichereinheiten zu gewähren und Speicherzuordnungen effektiv zu verwalten. 
---
= Erstellen Sie Hostgruppen auf Ihrem ASA R2-System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf einem ASA r2 System dient eine Hostgruppe als Mechanismus, um Hosts Zugriff auf Speichereinheiten zu gewähren. Eine Hostgruppe entspricht einer Initiatorgruppe für SCSI Hosts oder einem NVMe Subsystem für NVMe Hosts. Ein Host kann nur die Speichereinheiten sehen, die den Hostgruppen zugeordnet sind, denen er angehört. Wenn eine Hostgruppe einer Speichereinheit zugeordnet ist, können die Hosts, die Mitglieder dieser Gruppe sind, die Speichereinheit einbinden (Verzeichnisse und Dateistrukturen darauf erstellen).

Hostgruppen werden beim Erstellen Ihrer Speichereinheiten automatisch oder manuell erstellt. Es besteht die Möglichkeit, die folgenden Schritte zu nutzen, um Hostgruppen vor oder nach der Erstellung der Speichereinheiten zu erstellen.

.Schritte
. Wählen Sie im System Manager *Host* aus.
. Wählen Sie die Hosts aus, die Sie der Host-Gruppe hinzufügen möchten.
+
Nachdem Sie den ersten Host ausgewählt haben, wird die Option zum Hinzufügen zu einer Host-Gruppe über der Liste der Hosts angezeigt.

. Wählen Sie *zu Host-Gruppe hinzufügen*.
. Suchen Sie nach der Hostgruppe, der Sie den Host hinzufügen möchten, und wählen Sie sie aus.


.Was kommt als Nächstes?
Sie haben eine Hostgruppe erstellt und können nun link:provision-san-storage.html#map-the-storage-unit-to-a-host["ordnen Sie es einer Speichereinheit zu"] .
