---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Für optimale Leistung, Konfiguration und Unterstützung sollten Sie die Speichergrenzen von ASA r2 beachten. 
---
= Grenzen des ASA r2-Systemspeichers bestimmen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für optimale Leistung, Konfiguration und Support ist es wichtig, die Speichergrenzen von ASA r2 zu kennen.

Die Grenzwerte können je nach Ihrem ASA r2 System und Ihrer ONTAP Version variieren. Eine vollständige Liste der aktuellsten Grenzwerte für Ihr spezifisches System ist unter link:https://hwu.netapp.com/["NetApp Hardware Universe"^] verfügbar.


NOTE: Die Beschränkungen für virtuelle Maschinen (VMs) sind in Hardware Universe nicht aufgeführt. Die empfohlene maximale Anzahl an VMs pro HA-Paar beträgt 800 und pro Cluster 1.200, basierend auf den Systemvolumenbeschränkungen von ASA r2. Diese Beschränkung gilt nicht für VMs, die sich in VMFS-Datenspeichern befinden. Für VMFS-Datenspeicher gibt es keine maximale Anzahl an VMs.

.Über diese Aufgabe
ASA r2-Systeme sind im NetApp Hardware Universe unter *Produkte* als "ASA" Plattformen aufgeführt.

.Schritte
. Zu link:https://hwu.netapp.com["NetApp Hardware Universe"^] wechseln.
. *Produkte* auswählen.
. Unter *Plattformen* *ASA* als Systemtyp auswählen.
. Wählen Sie Ihr spezifisches System und anschließend Ihre ONTAP Version.
. *Ergebnisse anzeigen* auswählen.


.Ergebnisse
Die unterstützten Grenzwerte für Ihr spezifisches ASA r2-System und Ihre ONTAP-Version werden angezeigt.
