---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20,asa c30 
summary: Für optimale Performance, Konfiguration und Support sollten Sie die ASA r2 Storage-Grenzwerte kennen. 
---
= ASA r2 Storage-Grenzwerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für optimale Performance, Konfiguration und Support sollten Sie die ASA r2 Storage-Grenzwerte kennen.

ASA R2-Systeme unterstützen die folgenden Speichergrenzen:

[cols="3"]
|===
| Maximales Limit | Pro HA-Paar | Pro Cluster 


| Konsistenzgruppe | 256 | 256 


| Unternehmensanwendungen | 100 | 350 


| Nodes | 2 | 12 


| Replikationsgruppen | 50 | 50 


| Größe der Speicherverfügbarkeitszone | 2PB | 2 PB 


| Speichereinheiten | 10.000 | 30.000 


| Größe der Lagereinheit | 128 TB | 128 TB 


| Speichereinheiten pro Konsistenzgruppe | 256 | 256 


| Virtuelle Maschinen | 800 | 1200 
|===


== Grenzwerte für asynchrone SnapMirror -Beziehungen

Die folgenden Beschränkungen gelten für Speichereinheiten und Konsistenzgruppen in einer asynchronen SnapMirror -Replikationsbeziehung.

[cols="3"]
|===
| Maximales Limit | Pro HA-Paar | Pro Cluster 


| Konsistenzgruppen | 250 | 750 


| Speichereinheiten | 4.000 | 6.000 
|===


== Grenzen für die aktive Synchronisierungsbeziehung von SnapMirror

Die folgenden Beschränkungen gelten für Speichereinheiten und Konsistenzgruppen in einer SnapMirror Active Sync-Replikationsbeziehung.  SnapMirror Active Sync wird ab ONTAP 9.17.1 nur auf 2-Knoten-Clustern unterstützt.

[cols="2"]
|===
| Maximales Limit | Pro HA-Paar 


| Konsistenzgruppen | 50 


| Speichereinheiten | 400 
|===
.Finden Sie weitere Informationen
Eine vollständige Liste der aktuellen ASA r2-Speicherlimits finden Sie unter link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
