---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: Überwachen Sie Ihre Storage-Auslastung, um sicherzustellen, dass Sie die Storage-Kapazität haben, die Sie für aktuelle und zukünftige Workloads benötigen. 
searchtitle: Überwachen Sie die Speicherplatzauslastung mit ONTAP System Manager ASA r2 
---
= Überwachung der Auslastung von Clustern und Speichereinheiten auf ASA r2-Storage-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit ONTAP System Manager überwachen Sie Ihre Storage-Auslastung, um sicherzustellen, dass Sie die Storage-Kapazität haben, die Sie für aktuelle und zukünftige Workloads benötigen.



[[monitor-cluster-utilization]]
== Überwachen der Cluster-Auslastung

Überwachen Sie regelmäßig den von Ihrem Cluster verbrauchten Storage, um sicherzustellen, dass Sie bei Bedarf bereit sind, die Cluster-Kapazität zu erweitern, bevor der Speicherplatz knapp wird.

.Schritte
. Wählen Sie in System Manager *Dashboard* aus.
. Unter *Capacity* sehen Sie die Menge des physisch belegten Speicherplatzes und die Menge des verfügbaren Speicherplatzes auf Ihrem Cluster.
+
Das Datenreduzierungsverhältnis stellt den durch Storage-Effizienz eingesparten Speicherplatz dar.



.Was kommt als Nächstes?
Wenn in Ihrem Cluster der Speicherplatz knapp wird oder er nicht über die Kapazität verfügt, den zukünftigen Bedarf zu decken, link:../administer/increase-storage-capacity.html["Fügen Sie neue Laufwerke hinzu"] zu Ihrem ASA r2 System, um Ihre Speicherkapazität zu erhöhen.



[[monitor-storage-availability-zone-utilization]]
== Überwachung der Storage-Verfügbarkeitszonen-Auslastung

Jedes HA-Paar in einem ASA r2-System nutzt einen gemeinsamen Speicherpool, die sogenannte . Die storage availability zone hat Zugriff auf alle verfügbaren Festplatten im Speichersystem und ist für beide Knoten im HA-Paar sichtbar. Die Überwachung des verfügbaren Speicherplatzes Ihrer storage availability zones ermöglicht es Ihnen, die Nutzung bei Bedarf zu verringern oder die Kapazität zu erhöhen, sodass Sie keine fehlgeschlagenen Workloads aufgrund unzureichenden Speicherplatzes erleben.

Wenn Ihr Cluster 4 oder mehr Nodes enthält, können Sie die Menge des Speicherplatzes anzeigen, der von der Storage-Verfügbarkeitszone für jedes HA-Paar verwendet wird. Diese Metrik ist für 2-Node-Cluster nicht verfügbar.

Ab ONTAP 9.19.1 wird in System Manager *Insights* eine Warnung angezeigt, wenn eine Speicherverfügbarkeitszone in einem Ihrer ASA r2-System-HA-Paare ihre Kapazitätsgrenze erreicht. Weitere Informationen zu System Manager link:view-insights.html["Einblicke"].

.Schritte
. Wählen Sie im System Manager *Cluster* aus, und wählen Sie dann *Übersicht* aus.
+
Für jedes HA-Paar im Cluster wird eine Zusammenfassung der Storage-Verfügbarkeitszone-Auslastung angezeigt.

. Wenn Sie detailliertere Metriken benötigen, wählen Sie eine bestimmte Storage-Verfügbarkeit aus.
+
Unter *Übersicht* werden die Kapazität der Storage Availability Zone, der belegte Speicherplatz und das Datenreduktionsverhältnis angezeigt.

+
Unter *Speichereinheiten* wird eine Liste aller Speichereinheiten in der Speicherverfügbarkeitszone angezeigt.



.Was kommt als Nächstes?
Wenn der Speicherplatz in Ihrer Speicherverfügbarkeitszone knapp wird, link:../manage-data/move-storage-units.html["Speichereinheiten verschieben"] zu einer anderen Speicherverfügbarkeitszone wechseln, um die Speicherauslastung im Cluster auszugleichen, Snapshots löschen, um Speicherplatz freizugeben, oder zusätzliche Festplatten zu Ihren Knoten hinzufügen, um die Kapazität zu erhöhen.



[[monitor-storage-unit-utilization]]
== Überwachung der Auslastung der Speichereinheiten

Überwachen Sie den Storage-Verbrauch einer Storage-Einheit, um proaktiv die Größe der Storage-Einheit ganz nach Ihren Bedürfnissen zu erweitern.

.Schritte
. Wählen Sie im System Manager *Storage* aus.
. Wählen Sie die zu überwachende Speichereinheit aus, und wählen Sie dann *Übersicht*.
. Sehen Sie sich unter *Speicher* Folgendes an:
+
** Größe der Speichereinheit
** Menge des belegten Speicherplatzes
** Datenreduzierungsquote
+
Das Datenreduzierungsverhältnis stellt den durch Storage-Effizienz eingesparten Speicherplatz dar.

** Verwendeter Snapshot
+
Der von Snapshots verwendete Snapshot stellt die Größe des von Snapshots verwendeten Speichers dar.





.Was kommt als Nächstes?
Wenn sich die Speicherkapazität Ihrer Speichereinheit nähert, sollten Sie link:../manage-data/modify-storage-units.html["Ändern Sie die Speichereinheit"]sie vergrößern.
