---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: ONTAP aktualisiert automatisch die Firmware auf ASA r2-Systemen. Sie können System Manager verwenden, um automatische Updates zu deaktivieren und Updates anzuzeigen, bevor sie installiert werden. 
---
= Führen Sie ein Upgrade von ONTAP auf ASA r2 Storage-Systemen durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihre ONTAP Software auf Ihrem ASA r2 System aktualisieren, können Sie von neuen und verbesserten ONTAP Funktionen profitieren, mit denen Sie Kosten senken, kritische Workloads beschleunigen, die Sicherheit erhöhen und den Umfang der für Ihr Unternehmen verfügbaren Datensicherung erweitern können.

ONTAP Software-Upgrades für ASA r2 Systeme befolgen denselben Prozess wie Upgrades anderer ONTAP Systeme. Wenn Sie über einen aktiven SupportEdge-Vertrag für den digitalen Berater von Active IQ (auch als digitaler Berater bekannt) verfügen, sollten Sie link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Bereiten Sie das Upgrade mit Upgrade Advisor vor"^]. Upgrade Advisor bietet intelligente Funktionen, mit denen Sie die Unsicherheit und Risiken minimieren können, indem Sie den Cluster bewerten und einen konfigurationsspezifischen Upgrade-Plan erstellen. Wenn Sie keinen aktiven SupportEdge-Vertrag für Active IQ Digital Advisor haben, sollten Sie dies link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html["Vorbereitung auf das Upgrade ohne Upgrade Advisor"^]tun.

Nach der Vorbereitung auf das Upgrade wird empfohlen, Upgrades mit durchzuführenlink:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["Automatisierte unterbrechungsfreie Upgrades (ANDU) von System Manager"]. ANDU nutzt die Hochverfügbarkeits-(HA-)Failover-Technologie von ONTAP, um sicherzustellen, dass Cluster während des Upgrades Daten weiterhin ohne Unterbrechung bereitstellen.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Upgrades für die ONTAP Software"].
