---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: ONTAP -Software-Upgrades für ASA r2-Systeme folgen demselben Prozess wie Upgrades für andere ONTAP Systeme.  Wenn Sie Ihre ONTAP -Software auf Ihrem ASA r2-System aktualisieren, können Sie die Vorteile neuer und verbesserter ONTAP Funktionen nutzen. 
---
= Führen Sie ein Upgrade von ONTAP auf ASA r2 Storage-Systemen durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihre ONTAP Software auf Ihrem ASA r2 System aktualisieren, können Sie von neuen und verbesserten ONTAP Funktionen profitieren, mit denen Sie Kosten senken, kritische Workloads beschleunigen, die Sicherheit erhöhen und den Umfang der für Ihr Unternehmen verfügbaren Datensicherung erweitern können.

ONTAP-Software-Upgrades für ASA r2-Systeme folgen dem gleichen Prozess wie Upgrades für andere ONTAP Systeme. Es wird empfohlen, mit link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Vorbereitung Ihres Upgrades mit dem Upgrade Advisor in Active IQ Digital Advisor oder dem Upgrade Health Checker"] zu beginnen.

Nach der Vorbereitung auf das Upgrade wird empfohlen, Upgrades mit durchzuführenlink:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["Automatisierte unterbrechungsfreie Upgrades (ANDU) von System Manager"]. ANDU nutzt die Hochverfügbarkeits-(HA-)Failover-Technologie von ONTAP, um sicherzustellen, dass Cluster während des Upgrades Daten weiterhin ohne Unterbrechung bereitstellen.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Upgrades für die ONTAP Software"].
