---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'ASA r2-Systeme (ASA A1K, A90, A70, A50, A30, A20, C30) bieten eine einheitliche Hardware- und Softwarelösung für ein vereinfachtes Erlebnis für reine SAN-Kunden.' 
searchtitle: Erfahren Sie mehr über die Systeme ASA A1K, A90, A70, A50, A30, A20 und C30 
---
= Erfahren Sie mehr über ASA r2 Storage-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NetApp ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung, die das Erlebnis für reine SAN-Kunden vereinfacht. Auf einem ASA r2 System sind ONTAP Software und System Manager so optimiert, dass sie die wesentlichen SAN-Funktionen unterstützen, während Funktionen entfernt werden, die in SAN-Umgebungen nicht benötigt werden.

Folgende Systeme werden als ASA r2-Systeme klassifiziert:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


.Speichereinheiten und Konsistenzgruppen
Bei ASA r2-Systemen werden Storage-Einheiten mit Konsistenzgruppen eingesetzt:

* Eine _Storage unit_ stellt Ihren SAN-Hosts Speicherplatz für Datenoperationen zur Verfügung. Eine Storage-Einheit bezieht sich auf eine LUN für SCSI-Hosts oder einen NVMe-Namespace für NVMe-Hosts.
* _Eine Consistency Group_ ist eine Sammlung von Speichereinheiten, die als eine Einheit verwaltet werden.


ASA r2-Systeme verwenden Speichereinheiten mit Konsistenzgruppen, um die Speicherverwaltung und den Datenschutz zu vereinfachen. Beispielsweise kann eine Datenbank aus 10 Speichereinheiten in einer Konsistenzgruppe bestehen, wenn die gesamte Datenbank gesichert werden muss. Statt jede Speichereinheit einzeln zu sichern, lässt sich die gesamte Datenbank schützen, indem die Konsistenzgruppe gesichert wird.

.Datenschutz und Sicherheit
Um Ihre Daten vor böswilligen Angriffen wie Diebstahl oder Ransomware zu schützen, unterstützen ASA r2 Systeme einen Onboard Key Manager, eine zweischichtige Verschlüsselung, eine Multi-Faktor-Authentifizierung und eine Multi-Admin-Verifizierung. Sie können Snapshots auch an einen sekundären Speicherort replizieren und SnapLock für SnapVault verwenden, um die Ziel-Snapshots vor versehentlichem oder böswilligem Löschen zu schützen.

.Unterstützte Protokolle, Multipathing und Konfigurationen
ASA r2 Systeme unterstützen alle SAN-Protokolle (iSCSI, FC, NVMe/FC, NVMe/TCP). Alle Protokolle unterstützen eine symmetrische Aktiv/Aktiv-Architektur für Multipathing, sodass alle Pfade zwischen den Hosts und dem Speicher aktiv/optimiert sind. Die Protokolle iSCSI und NVMe/TCP unterstützen Netzwerk- und Direktanschlusskonfigurationen für alle unterstützten ONTAP Versionen. Die Protokolle FC und NVMe/FC unterstützen Netzwerkkonfigurationen für alle unterstützten ONTAP Versionen und ab ONTAP 9.19.1 auch Direktanschlusskonfigurationen. ASA r2 Systeme unterstützen keine Cluster-Mischung mit ASA, AFF oder FAS Systemen.

* Weitere Informationen zu link:https://docs.netapp.com/us-en/ontap/san-admin/multipath-automatic-lif-failover-support.html["SAN Multipath-Unterstützung"^].
* Weitere Informationen zu link:https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-ha-pairs-reference.html["Konfigurationen für iSCSI und NVMe/TCP Protokolle"^].
* Weitere Informationen zu link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["Konfigurationen für FC und NVMe/FC-Protokolle"^].


.Verwandte Informationen
* Weitere Informationen zur Unterstützung und Einschränkungen von ASA r2-Systemen finden Sie im link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Erfahren Sie mehr über link:../learn-more/hardware-comparison.html["Den ASA r2 Systemen im Vergleich zu den ASA Systemen"].
* Erfahren Sie mehr über die link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^].

