---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'ASA r2-Systeme (ASA A1K, A90, A70, A50, A30, A20, C30) bieten eine einheitliche Hardware- und Softwarelösung für ein vereinfachtes Erlebnis für reine SAN-Kunden.' 
searchtitle: Erfahren Sie mehr über die Systeme ASA A1K, A90, A70, A50, A30, A20 und C30 
---
= Erfahren Sie mehr über ASA r2 Storage-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NetApp ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung, mit der eine vereinfachte Erfahrung speziell für die Anforderungen reiner SAN-Kunden erzielt wird.

Die folgenden ASA-Plattformen werden als ASA r2-Systeme klassifiziert:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


ASA r2 Systeme unterstützen alle SAN-Protokolle (iSCSI, FC, NVMe/FC, NVMe/TCP). Die Protokolle iSCSI, FC, NVMe/FC und NVMe/TCP unterstützen die symmetrische aktiv/aktiv-Architektur für Multipathing, sodass alle Pfade zwischen Hosts und Storage aktiv/optimiert sind. Die iSCSI- und NVMe/TCP-Protokolle unterstützen direkte Pfade zwischen den Hosts und dem Storage.

Auf einem ASA r2 System sind ONTAP Software und System Manager optimiert, um die grundlegenden SAN-Funktionen zu unterstützen und gleichzeitig Funktionen zu entfernen, die in SAN-Umgebungen nicht unterstützt werden.

Bei ASA r2-Systemen werden Storage-Einheiten mit Konsistenzgruppen eingesetzt:

* Eine _Storage unit_ stellt Ihren SAN-Hosts Speicherplatz für Datenoperationen zur Verfügung. Eine Storage-Einheit bezieht sich auf eine LUN für SCSI-Hosts oder einen NVMe-Namespace für NVMe-Hosts.
* _Eine Consistency Group_ ist eine Sammlung von Speichereinheiten, die als eine Einheit verwaltet werden.


ASA r2-Systeme verwenden Speichereinheiten mit Konsistenzgruppen, um die Speicherverwaltung und den Datenschutz zu vereinfachen.  Angenommen, Sie haben eine Datenbank, die aus 10 Speichereinheiten in einer Konsistenzgruppe besteht, und Sie müssen die gesamte Datenbank sichern.  Anstatt jede Speichereinheit einzeln zu sichern, können Sie die gesamte Datenbank schützen, indem Sie die Konsistenzgruppe sichern.

Um Ihre Daten vor böswilligen Angriffen wie Diebstahl oder Ransomware zu schützen, unterstützen ASA r2-Systeme einen integrierten Schlüsselmanager, Dual-Layer-Verschlüsselung, Multi-Faktor-Authentifizierung und Multi-Admin-Verifizierung. Manipulationssichere Snapshots werden auch auf sekundären ASA r2-Systemen unterstützt.

ASA r2-Systeme unterstützen keine gemeinsame Verwendung von Clustern mit aktuellen ASA-, AFF- oder FAS-Systemen.

.Finden Sie weitere Informationen
* Weitere Informationen zur Unterstützung und Einschränkungen von ASA r2-Systemen finden Sie im link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Erfahren Sie mehr über link:../learn-more/hardware-comparison.html["Den ASA r2 Systemen im Vergleich zu den ASA Systemen"].
* Erfahren Sie mehr über die link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"].

