---
sidebar: sidebar 
permalink: data-protection/configure-ontap-mediator.html 
keywords: asa r2, data protection, protect data, configure mediator, ontap mediator, cloud mediator, self-signed, ca, certificates 
summary: Erfahren Sie, wie Sie den ONTAP Mediator oder ONTAP Cloud Mediator mit selbstsignierten oder Drittanbieter-Zertifikaten für ASA r2-Systeme konfigurieren. 
---
= Konfigurieren Sie ONTAP Mediator oder ONTAP Cloud Mediator auf ASA r2-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen ONTAP Mediator oder ONTAP Cloud Mediator konfigurieren, bevor Sie SnapMirror Active Sync zur Clusterüberwachung nutzen können. ONTAP Mediator und ONTAP Cloud Mediator bieten beide einen persistenten und abgeschirmten Speicher für Hochverfügbarkeits-Metadaten (HA), die von den ONTAP Clustern in einer SnapMirror Active Sync-Beziehung verwendet werden. Darüber hinaus bieten beide Mediatoren eine synchrone Knotenzustandsabfragefunktion zur Unterstützung der Quorumbestimmung und dienen als Ping-Proxy zur Controller-Aktivitätserkennung.

.Bevor Sie beginnen
Wenn Sie ONTAP Cloud Mediator verwenden, überprüfen Sie, ob Ihr ASA r2-System die erforderlichen link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html["Voraussetzungen"^] .

.Schritte
. Wählen Sie im System Manager *Schutz > Übersicht*.
. Wählen Sie im rechten Bereich unter *Mediatoren* die Option *Mediator hinzufügen* aus.
. Wählen Sie den *Mediatortyp* aus.
. Geben Sie für einen *Cloud*-Mediator die Organisations-ID, die Client-ID und das Client-Geheimnis ein. Geben Sie für einen *On-Premises*-Mediator die IP-Adresse, den Port, den Mediator-Benutzernamen und das Mediator-Passwort ein.
. Wählen Sie den Cluster-Peer aus der Liste der berechtigten Cluster-Peers aus oder wählen Sie *Cluster-Peer hinzufügen*, um einen neuen hinzuzufügen.
. Fügen Sie die Zertifikatsinformationen hinzu
+
** Wenn Sie ein selbstsigniertes Zertifikat verwenden, kopieren Sie den Inhalt des `intermediate.crt` Datei und fügen Sie sie in das Feld *Zertifikat* ein, oder wählen Sie *Importieren*, um zum `intermediate.crt` Datei und importieren Sie die Zertifikatsinformationen.
** Wenn Sie ein Drittanbieterzertifikat verwenden, geben Sie die Zertifikatsinformationen in das Feld *Zertifikat* ein.


. Wählen Sie *Hinzufügen*.


.Was kommt als Nächstes?
Nachdem Sie den Mediator initialisiert haben, können Sie link:configure-snapmirror-active-sync.html["Konfigurieren Sie SnapMirror Active Sync"] um eine Kopie Ihrer Daten an einem sekundären Standort zu erstellen und Ihren Hostanwendungen im Katastrophenfall ein automatisches und transparentes Failover zu ermöglichen.
