---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: Verwenden Sie Consistency Groups, um verschiedene Aktionen für mehrere Speichereinheiten gleichzeitig durchzuführen, anstatt einzeln auf jeder Einheit Aktionen durchzuführen. 
---
= Erfahren Sie mehr über ONTAP -Konsistenzgruppen auf ASA r2-Speichersystemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Konsistenzgruppe ist eine Sammlung von Speichereinheiten, die als eine einzige Einheit verwaltet werden.  Verwenden Sie Konsistenzgruppen für eine vereinfachte Speicherverwaltung.

Angenommen, Sie haben eine Datenbank, die aus 10 Speichereinheiten in einer Konsistenzgruppe besteht, und Sie müssen die gesamte Datenbank sichern. Anstatt jede Speichereinheit zu sichern, können Sie die gesamte Datenbank sichern, indem Sie der Konsistenzgruppe einfach den Snapshot-Datenschutz hinzufügen.  Das Sichern der Speichereinheiten als Konsistenzgruppe statt einzeln bietet auch eine konsistente Sicherung aller Einheiten, während das Sichern einzelner Einheiten möglicherweise zu Inkonsistenzen führen kann.

Ab ONTAP 9.16.1 können Sie mit System Manager hierarchische Konsistenzgruppen auf Ihrem ASA r2-System erstellen.  In einer hierarchischen Struktur werden eine oder mehrere Konsistenzgruppen als untergeordnete Elemente unter einer übergeordneten Konsistenzgruppe konfiguriert.

Hierarchische Konsistenzgruppen ermöglichen es Ihnen, individuelle Snapshot-Richtlinien auf jede untergeordnete Konsistenzgruppe anzuwenden und die Snapshots aller untergeordneten Konsistenzgruppen als eine Einheit auf ein Remote-Cluster zu replizieren, indem Sie das übergeordnete Objekt replizieren. Dadurch wird die Datensicherung und das Management komplexer Datenstrukturen vereinfacht. Beispiel: Angenommen, Sie erstellen eine übergeordnete Konsistenzgruppe mit dem Namen, `SVM1_app` die zwei untergeordnete Konsistenzgruppen enthält: `SVM1app_data` Für Applikationsdaten und `SVM1app_logs` Anwendungsprotokolle. Snapshots von `SVM1app_data` werden alle 15 Minuten erstellt und stündlich erstellt `SVM1app_logs`. Die übergeordnete Konsistenzgruppe `SVM1_app,` verfügt über eine SnapMirror-Richtlinie, die die Snapshots sowohl von als auch `SVM1app_logs` alle 24 Stunden in einem Remote Cluster repliziert `SVM1app_data`. Die übergeordnete Konsistenzgruppe `SVM1_app` wird als eine einzelne Einheit gemanagt, die untergeordneten Konsistenzgruppen werden als separate Einheiten gemanagt.



== Konsistenzgruppen in Replikationsbeziehungen

Ab ONTAP 9.17.1 können Sie die folgenden Geometrieänderungen an Konsistenzgruppen in einer asynchronen Replikationsbeziehung oder in einer SnapMirror -Active-Sync-Beziehung vornehmen, ohne die Beziehung zu unterbrechen oder zu löschen.  Wenn in der primären Konsistenzgruppe eine Geometrieänderung auftritt, wird die Änderung in die sekundäre Konsistenzgruppe repliziert.

* link:manage-consistency-groups-add-remove-storage-units.html["Ändern Sie die Größe einer Speichereinheit"]durch Hinzufügen oder Entfernen von Speichereinheiten.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["Fördern einer einzelnen Konsistenzgruppe"]zu einer übergeordneten Konsistenzgruppe.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["Herabstufen einer übergeordneten Konsistenzgruppe"]zu einer einzigen Konsistenzgruppe.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["Trennen einer untergeordneten Konsistenzgruppe"]aus einer übergeordneten Konsistenzgruppe.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["Erstellen einer untergeordneten Konsistenzgruppe"]unter Verwendung einer vorhandenen Konsistenzgruppe.


In ONTAP 9.16.1 müssen Sielink:snapmirror-active-sync-break-relationship.html["Unterbrechen Sie die asynchrone Replikationsbeziehung"] Undlink:snapmirror-active-sync-delete-relationship.html["Löschen Sie die SnapMirror Active Sync-Beziehung"] bevor Sie Geometrieänderungen an der Konsistenzgruppe vornehmen.
