---
sidebar: sidebar 
permalink: data-protection/snapmirror-active-sync-confirm-cluster-configuration.html 
keywords: asa r2, data protection, business continuity, snapmirror active sync, cluster configuration 
summary: Zeigen Sie Warnungen vor potenziellen Ransomware-Angriffen an und ergreifen Sie Maßnahmen im System Manager. 
---
= Bestätigen Sie Ihre ASA R2-Clusterkonfiguration, bevor Sie SnapMirror Active Sync konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync nutzt Peering-Cluster, um Ihre Daten im Falle eines Failovers zu schützen. Bevor Sie SnapMirror Active Sync konfigurieren, sollten Sie sicherstellen, dass Ihre ASA R2-Cluster in einer unterstützten Peering-Beziehung stehen und weitere Konfigurationsanforderungen erfüllen.

.Schritte
. Bestätigen Sie, dass zwischen den Clustern eine Cluster-Peering-Beziehung besteht.
+

NOTE: Der Standard-IP-Bereich wird von SnapMirror Active Sync für Cluster-Peer-Beziehungen benötigt. Ein benutzerdefinierter IP-Bereich wird nicht unterstützt.

+
link:snapshot-replication.html#step-1-create-a-cluster-peer-relationship["Erstellen einer Cluster-Peer-Beziehung"] .

. Bestätigen Sie, dass zwischen den virtuellen Speichermaschinen (VMs) auf jedem Cluster eine Peer-Beziehung besteht.
+
link:create-svm-peer-relationship.html["Erstellen einer Intercluster-Speicher-VM-Peer-Beziehung"^] .

. Bestätigen Sie, dass auf jedem Knoten im Cluster mindestens ein LIF erstellt wird.
+
link:../administer/manage-client-vm-access.html#create-a-lif-network-interface["Erstellen eines LIF"]

. Bestätigen Sie, dass die erforderlichen Speichereinheiten erstellt und Hostgruppen zugeordnet wurden.
+
link:../manage-data/provision-san-storage.html#create-storage-units["Erstellen Sie eine Speichereinheit"] Und link:../manage-data/provision-san-storage.html#map-the-storage-unit-to-a-host["Ordnen Sie die Speichereinheit einer Hostgruppe zu"] .

. Scannen Sie den Anwendungshost erneut, um neue Speichereinheiten zu erkennen.


.Was kommt als Nächstes?
Nachdem Sie Ihre Clusterkonfiguration bestätigt haben, können Sie link:install-ontap-mediator.html["ONTAP Mediator installieren"] .
