---
sidebar: sidebar 
permalink: release-notes/whats-new-9160.html 
keywords: 'what"s new, release notes, 9.16.0, asa r2, asa a1k, asa a90, asa a70' 
summary: Erfahren Sie mehr über die neuen Funktionen in ONTAP 9.16.0 für ASA r2 Systeme. 
---
= Neuerungen in ONTAP 9.16.0 für ASA r2-Systeme
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen Funktionen in ONTAP 9.16.0 für ASA r2 Systeme.



== Systeme

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| Systeme  a| 
Folgende NetApp ASA r2-Systeme sind verfügbar.  Diese Systeme bieten eine einheitliche Hardware- und Softwarelösung, die ein vereinfachtes Benutzererlebnis schafft, das speziell auf die Bedürfnisse von SAN-only-Kunden zugeschnitten ist.

* ASA A1K
* ASA A70
* ASA A90


|===


== System Manager

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| link:../get-started/learn-about.html["Optimierter Support für reine SAN-Kunden"] | System Manager ist optimiert, um wichtige SAN-Funktionalität zu unterstützen, während gleichzeitig die Transparenz von Funktionen und Funktionen entfällt, die in SAN-Umgebungen nicht unterstützt werden. 
|===


== Storage-Management

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| link:../manage-data/provision-san-storage.html["Vereinfachtes Storage-Management"]  a| 
ASA r2-Systeme führen Storage-Einheiten mit Konsistenzgruppen ein, was das Storage-Management vereinfacht.

* Eine _Storage unit_ stellt Ihren SAN-Hosts Speicherplatz für Datenoperationen zur Verfügung. Eine Storage-Einheit bezieht sich auf eine LUN für SCSI-Hosts oder einen NVMe-Namespace für NVMe-Hosts.
* _Eine Consistency Group_ ist eine Sammlung von Speichereinheiten, die als eine Einheit verwaltet werden.


|===


== Datensicherheit

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| link:../secure-data/encrypt-data-at-rest.html["Onboard-Verschlüsselungsmanagement und Dual-Layer-Verschlüsselung"]  a| 
ASA r2 Systeme unterstützen einen integrierten Schlüsselmanager und eine Dual-Layer-Verschlüsselung (Hardware und Software).

|===